import { createHash } from 'node:crypto';
import type { Author, Evidence, EvidenceType, Identifier, Locator, ResearchWork, SourceQuality } from '../models/research.js';

export function normalizeDoi(value: string): string { return value.trim().replace(/^https?:\/\/(?:doi\.org|dx\.doi\.org)\//i, '').replace(/^doi:\s*/i, '').toLowerCase().replace(/[.,;:]+$/, ''); }
export function normalizeArxivId(value: string): string { return value.trim().replace(/^https?:\/\/(arxiv\.org\/abs\/|export\.arxiv\.org\/api\/query\?id_list=)/i, '').replace(/^arxiv:/i, '').replace(/v\d+$/i, ''); }
export function normalizeAuthorName(name: string): string { return name.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^\p{L}\p{N} ]/gu, ' ').replace(/\s+/g, ' ').trim().toLowerCase(); }
export function author(name: string, orcid?: string): Author { return orcid ? { name, normalizedName: normalizeAuthorName(name), orcid } : { name, normalizedName: normalizeAuthorName(name) }; }
export function paperId(title: string, authors: Author[], doi?: string, arxiv?: string): string { const key = doi ? `doi:${normalizeDoi(doi)}` : arxiv ? `arxiv:${normalizeArxivId(arxiv)}` : `${title}|${authors.map(a => a.normalizedName).join('|')}`; return `work_${createHash('sha256').update(key.toLowerCase()).digest('hex').slice(0, 16)}`; }
export function citationText(title: string, authors: Author[], year?: number, locator?: Locator): string { const names = authors.length <= 3 ? authors.map(a => a.name).join(', ') : `${authors[0]?.name ?? 'Unknown'} et al.`; const loc = locator ? [locator.section && `§${locator.section}`, locator.page && `p. ${locator.page}`, locator.table && locator.table].filter(Boolean).join(', ') : ''; return `[${names}${year ? `, ${year}` : ''}${loc ? `, ${loc}` : ''}]`; }
export function makeEvidence(sourceId: string, work: ResearchWork, evidence: string, evidenceType: EvidenceType = 'DIRECT', sourceQuality: SourceQuality = 'A', locator?: Locator): Evidence { const evidenceId = `ev_${createHash('sha256').update(`${sourceId}:${evidence}:${JSON.stringify(locator ?? {})}`).digest('hex').slice(0, 16)}`; const identifiers: Identifier = {}; if (work.doi) identifiers.doi = work.doi; if (work.arxivId) identifiers.arxiv = work.arxivId; if (work.semanticScholarId) identifiers.semanticScholar = work.semanticScholarId; if (work.openAlexId) identifiers.openAlex = work.openAlexId; return { evidenceId, sourceId, authors: work.authors, title: work.title, ...(work.year !== undefined ? { year: work.year } : {}), identifiers, ...(locator ? { locator } : {}), evidenceType, sourceQuality, evidence, citationText: citationText(work.title, work.authors, work.year, locator) }; }
export function bibtex(work: ResearchWork): string { const key = `${work.authors[0]?.normalizedName.split(' ')[0] ?? 'unknown'}${work.year ?? 'nd'}${work.paperId.slice(-6)}`; return `@article{${key},\n  title = {${work.title}},\n  author = {${work.authors.map(a => a.name).join(' and ')}},\n  year = {${work.year ?? ''}}${work.doi ? `,\n  doi = {${work.doi}}` : ''}${work.arxivId ? `,\n  eprint = {${work.arxivId}}` : ''}\n}`; }
