import type { HubItem, PaperLink } from '../providers/huggingface.js';
import type { Evidence, ResearchWork } from '../models/research.js';
import { makeEvidence } from './citations.js';

export interface ReconciledPaperLink extends PaperLink { status: 'VERIFIED' | 'UNVERIFIED'; paperId?: string; }
export interface ReconciledPaperLinks { itemId: string; links: ReconciledPaperLink[]; }
export type PaperResolver = (link: PaperLink) => string | undefined;
export interface RepositoryLinkSource { url?: string; blobSha?: string; commitSha?: string; lineStart?: number; lineEnd?: number; }
export interface RepositoryLinkAssessment { level: 'PAPER_REFERENCED' | 'AUTHOR_OVERLAP' | 'UNVERIFIED'; implementationStatus: 'UNKNOWN'; reasons: string[]; source?: RepositoryLinkSource; }
export function assessRepositoryLink(repository: { owner: string }, paper: { arxivId?: string; doi?: string; authors: Array<{ normalizedName: string; name: string }> }, readme = '', source?: RepositoryLinkSource): RepositoryLinkAssessment { const reasons:string[]=[]; const text=readme.toLowerCase(); const arxiv=paper.arxivId?.toLowerCase(); const doi=paper.doi?.toLowerCase(); const paperReferenced=Boolean((arxiv && text.includes(arxiv)) || (doi && text.includes(doi))); if (paperReferenced) { reasons.push('README references the paper identifier'); const lines=readme.split(/\r?\n/); const lineIndex=lines.findIndex(line=>(arxiv && line.toLowerCase().includes(arxiv)) || (doi && line.toLowerCase().includes(doi))); if(lineIndex>=0) source={...source,lineStart:lineIndex+1,lineEnd:lineIndex+1}; } const owner=repository.owner.toLowerCase().replace(/[^a-z0-9]/g,''); const authorOverlap=paper.authors.some(author=>author.normalizedName.toLowerCase().split(/[^a-z0-9]+/).some(part=>part.length>=4&&part===owner)); if (authorOverlap) reasons.push('Repository owner overlaps a paper author name'); return {level:paperReferenced?'PAPER_REFERENCED':authorOverlap?'AUTHOR_OVERLAP':'UNVERIFIED',implementationStatus:'UNKNOWN',reasons,...(source?{source}:{})}; }
export function repositoryLinkEvidence(repository: { htmlUrl: string; fullName: string }, paper: ResearchWork, assessment: RepositoryLinkAssessment): Evidence[] { if (assessment.level === 'UNVERIFIED') return []; const source=assessment.source; const locator=source ? { ...(source.url ? {} : {}), repositoryPath:'README.md', ...(source.lineStart !== undefined ? {repositoryLineStart:source.lineStart,repositoryLineEnd:source.lineEnd} : {}), ...(source.commitSha ? {commitSha:source.commitSha} : {}) } : undefined; return [makeEvidence(repository.htmlUrl,paper,`GitHub repository ${repository.fullName}: ${assessment.reasons.join('; ')}`,assessment.level==='PAPER_REFERENCED'?'SECONDARY_SOURCE':'DERIVED','D',locator)]; }
export function reconcilePaperLinks(item: HubItem, resolver: PaperResolver): ReconciledPaperLinks { return { itemId:item.id, links:item.paperLinks.map(link=>{ const paperId=resolver(link); return paperId ? {...link,status:'VERIFIED' as const,paperId} : {...link,status:'UNVERIFIED' as const}; }) }; }
