import type { ParsedDocument } from '../ingestion/document.js';
import type { Locator } from '../models/research.js';

export type FactValue=string|number|boolean|string[];
export type FactSourceClass='PAPER'|'APPENDIX'|'README'|'CONFIG'|'TRAINING_SCRIPT'|'MODEL_CARD'|'PROVIDER_METADATA'|'OTHER';
export type FactSupportState='EXPLICIT'|'NORMALIZED_EXPLICIT'|'COMPOSITE_EXPLICIT'|'CONFLICTING'|'UNKNOWN';
export interface ResearchFact { factId:string; predicate:string; value:FactValue; rawValue:string; sourceId:string; sourceClass:FactSourceClass; locator:Locator; rawEvidence:string; scope?:string; stage?:string; extractionMethod:string; supportState:FactSupportState; }
const patterns:Array<[string,string,RegExp,string,string?]>= [
 ['training.objective','text infilling',/text[-\s]+infilling/i,'denoising objective'],['training.objective','contrastive learning',/contrastive (?:learning|objective|loss|task)/i,'contrastive objective'],['training.objective','span corruption',/span[-\s]+corruption/i,'corruption objective'],['training.objective','masked language model',/masked language model/i,'masked objective'],['training.objective','next sentence prediction',/next sentence prediction/i,'pretraining objective'],
 ['architecture.formulation','text-to-text',/text[-\s]to[-\s]text/i,'task formulation'],['architecture.formulation','cross-attention',/cross[-\s]+attention/i,'multimodal connection'],
 ['system.parallelism','tensor model parallelism',/tensor model parallel(?:ism)?|intra[-\s]layer model parallel(?:ism)?/i,'tensor parallelism'],['system.parallelism','data parallelism',/data parallel(?:ism)?/i,'data parallelism'],['system.parallelism','pipeline model parallelism',/pipeline model parallel(?:ism)?/i,'pipeline parallelism'],
 ['architecture.moe','sparse mixture of experts',/sparse[-\s]+mixture[-\s]+of[-\s]+experts|mixture[-\s]+of[-\s]+experts/i,'mixture of experts'],['architecture.operator','long convolutions',/long[-\s]+convolution/i,'long convolution operator'],
 ['system.zero_stage','optimizer states',/optimizer states?/i,'partitioned optimizer state'],['system.zero_stage','gradients',/\bgradients\b/i,'partitioned gradients'],['system.zero_stage','parameters',/\bparameters\b/i,'partitioned parameters'],
 ['retrieval.component','retriever',/\bretriever\b/i,'retrieval component'],['retrieval.component','generator',/\bgenerator\b/i,'generation component'],['model.component','Q-Former',/Q[-\s]?Former|Querying Transformer/i,'bridge module'],
 ['evaluation.regime','zero-shot',/zero[- ]shot/i,'evaluation regime'],['evaluation.regime','one-shot',/one[- ]shot/i,'evaluation regime'],['evaluation.regime','few-shot',/few[- ]shot/i,'evaluation regime'],
 ['training.stage','SFT',/\bSFT\b|supervised fine[-\s]tuning/i,'training stage'],['training.stage','reward model',/reward model/i,'training stage'],['training.stage','PPO',/\bPPO\b|proximal policy optimization/i,'training stage'],
 ['architecture.attention','exact',/\bexact attention\b/i,'attention property'],['architecture.attention','FlashAttention',/FlashAttention/i,'attention implementation'],['architecture.attention','grouped-query attention',/grouped[-\s]+query[-\s]+attention/i,'attention topology'],
 ['reasoning.trace_type','thought',/\bthought\b/i,'agent trace element'],['reasoning.trace_type','action',/\baction\b/i,'agent trace element'],['reasoning.trace_type','observation',/\bobservation\b/i,'agent trace element'],['reasoning.trace_type','intermediate reasoning steps',/intermediate(?: reasoning)? steps?|reasoning steps/i,'reasoning trace'],
 ['training.preference_method','DPO',/direct preference optimization|\bDPO\b/i,'preference method'],['training.preference_method','ORPO',/odds[-\s]+ratio[-\s]+preference[-\s]+optimization|\bORPO\b/i,'preference method'],['training.algorithm','GRPO',/\bGRPO\b|group[-\s]+relative[-\s]+policy[-\s]+optimization/i,'reinforcement algorithm'],['retrieval.interaction','late interaction',/late[-\s]+interaction/i,'retrieval interaction'],['retrieval.retriever','dual-encoder dense retriever',/dual[-\s]+encoder|dense passage retriev/i,'retriever architecture'],
 ['architecture.attention','multi-head attention',/multi[-\s]+head attention/i,'attention topology'],['architecture.attention','multi-query attention',/multi[-\s]+query attention/i,'attention topology'],['architecture.attention','sliding-window attention',/sliding[-\s]+window attention/i,'attention topology']
];
function normalized(text:string):string{return text.normalize('NFKD').replace(/[‐‑‒–—−]/g,'-').replace(/([A-Za-z])-\s+([A-Za-z])/g,'$1$2').replace(/\s+/g,' ');}
function sentence(text:string,index:number):string{const start=Math.max(text.lastIndexOf('.',index)+1,text.lastIndexOf('\n',index)+1),end=text.indexOf('.',index);return text.slice(start,end<0?text.length:end+1).trim();}
export function extractResearchFacts(document:ParsedDocument):ResearchFact[]{const facts:ResearchFact[]=[];for(const section of document.sections){const text=normalized(section.text);for(const [predicate,value,pattern,method,stage] of patterns){const match=pattern.exec(text);if(!match)continue;const rawEvidence=sentence(section.text,match.index);const rawValue=match[0];const sourceClass:FactSourceClass=section.isAppendix?'APPENDIX':'PAPER';const factId=`fact-${document.url}-${predicate}-${value}`;facts.push({factId,predicate,value,rawValue,sourceId:document.url,sourceClass,locator:{section:section.heading,...(section.page===undefined?{}:{page:section.page}),...(section.pageId===undefined?{}:{pageId:section.pageId})},rawEvidence, ...(stage?{stage}:{}),extractionMethod:method,supportState:'NORMALIZED_EXPLICIT'});}}const unique=new Map<string,ResearchFact>();for(const fact of facts){const key=`${fact.predicate}:${JSON.stringify(fact.value)}:${fact.sourceId}`;if(!unique.has(key))unique.set(key,fact);}return [...unique.values()];}
