import type { ParsedDocument } from '../ingestion/document.js';
import type { Locator } from '../models/research.js';

export type FactValue=string|number|boolean|string[];
export type FactSourceClass='PAPER'|'APPENDIX'|'README'|'CONFIG'|'TRAINING_SCRIPT'|'MODEL_CARD'|'PROVIDER_METADATA'|'OTHER';
export type FactSupportState='EXPLICIT'|'NORMALIZED_EXPLICIT'|'COMPOSITE_EXPLICIT'|'CONFLICTING'|'UNKNOWN';
export interface ResearchFact { factId:string; predicate:string; value:FactValue; rawValue:string; sourceId:string; sourceClass:FactSourceClass; locator:Locator; rawEvidence:string; scope?:string; stage?:string; extractionMethod:string; supportState:FactSupportState; }
export interface CandidateEvidence { candidatePredicate:string; rawText:string; sourceId:string; locator:Locator; section:string; context:string; trigger:string; }
const patterns:Array<[string,string,RegExp,string,string?]>= [
 ['training.objective','text infilling',/text[-\s]+infilling/i,'denoising objective'],['training.objective','replaced token detection',/replaced token detection/i,'discriminator objective'],['training.objective','contrastive learning',/contrastive (?:learning|objective|loss|task)/i,'contrastive objective'],['training.objective','span corruption',/span[-\s]+corruption/i,'corruption objective'],['training.objective','masked reconstruction',/masked reconstruction|masked autoencoding|reconstruct(?:ing|ion) masked/i,'masked reconstruction objective'],['training.objective','knowledge distillation',/knowledge distillation/i,'distillation objective'],['training.objective','masked language model',/masked language model/i,'masked objective'],['training.objective','next sentence prediction',/next sentence prediction/i,'pretraining objective'],
 ['architecture.formulation','text-to-text',/text[-\s]to[-\s]text/i,'task formulation'],['architecture.formulation','image patches',/image patches|patch embeddings|patch tokens/i,'vision token formulation'],['model.formulation','decoder-only Transformer',/decoder[-\s]+only(?: transformer)?|transformer decoder/i,'language-model architecture'],['model.formulation','multimodal model',/multimodal|vision[-\s]+language/i,'multimodal capability'],['architecture.recurrence','segment-level recurrence',/segment[-\s]+level recurrence|recurrence mechanism/i,'recurrent memory'],
 ['system.parallelism','tensor model parallelism',/tensor model parallel(?:ism)?|intra[-\s]layer model parallel(?:ism)?/i,'tensor parallelism'],['system.parallelism','data parallelism',/data parallel(?:ism)?/i,'data parallelism'],['system.parallelism','pipeline model parallelism',/pipeline model parallel(?:ism)?/i,'pipeline parallelism'],
 ['architecture.moe','mixture of experts',/sparse[-\s]+mixture[-\s]+of[-\s]+experts|mixture[-\s]+of[-\s]+experts/i,'mixture of experts'],['architecture.operator','long convolutions',/long[-\s]+convolution/i,'long convolution operator'],
 ['system.zero_stage','optimizer states',/optimizer states?/i,'partitioned optimizer state'],['system.zero_stage','gradients',/\bgradients\b/i,'partitioned gradients'],['system.zero_stage','parameters',/\bparameters\b/i,'partitioned parameters'],
 ['retrieval.component','retriever',/\bretriever\b/i,'retrieval component'],['retrieval.component','generator',/\bgenerator\b/i,'generation component'],['model.component','Q-Former',/Q[-\s]?Former|Querying Transformer/i,'bridge module'],
 ['evaluation.regime','zero-shot',/zero[- ]shot/i,'evaluation regime'],['evaluation.regime','one-shot',/one[- ]shot/i,'evaluation regime'],['evaluation.regime','few-shot',/few[- ]shot/i,'evaluation regime'],
 ['training.stage','instruction fine-tuning',/instruction[-\s]*fine[-\s]*tun\w*/i,'training stage'],['training.stage','SFT',/\bSFT\b|supervised fine[-\s]tuning/i,'training stage'],['training.stage','fine-tuning',/\bfine[-\s]tun\w*/i,'training stage'],['training.stage','pretraining',/\bpre[-\s]?training\b/i,'training stage'],['training.stage','reward model',/reward model/i,'training stage'],['training.stage','PPO',/\bPPO\b|proximal policy optimization/i,'training stage'],
 ['architecture.attention','exact',/\bexact attention\b/i,'attention property'],['architecture.attention','FlashAttention',/FlashAttention/i,'attention implementation'],['architecture.attention','grouped-query attention',/grouped[-\s]+query[-\s]+attention/i,'attention topology'],['architecture.attention','linear attention',/linear[-\s]+attention|linear[-\s]+complexity/i,'linear attention'],['architecture.attention','locality-sensitive hashing attention',/locality[-\s]+sensitive hashing|LSH attention/i,'hashed attention'],['architecture.attention','shifted-window attention',/shifted[-\s]+window|shifted windows/i,'windowed attention'],
 ['reasoning.trace_type','thought',/\bthought\b/i,'agent trace element'],['reasoning.trace_type','action',/\baction\b/i,'agent trace element'],['reasoning.trace_type','observation',/\bobservation\b/i,'agent trace element'],['reasoning.trace_type','intermediate reasoning steps',/intermediate(?: reasoning)? steps?|reasoning steps/i,'reasoning trace'],
 ['training.preference_method','DPO',/direct preference optimization|\bDPO\b/i,'preference method'],['training.preference_method','ORPO',/odds[-\s]+ratio[-\s]+preference[-\s]+optimization|\bORPO\b/i,'preference method'],['training.algorithm','GRPO',/\bGRPO\b|group[-\s]+relative[-\s]+policy[-\s]+optimization/i,'reinforcement algorithm'],['evaluation.method','pairwise judging',/pairwise[-\s]+(?:comparison|judg)|LLM[-\s]+as[-\s]+a[-\s]+judge/i,'evaluation method'],['retrieval.interaction','late interaction',/late[-\s]+interaction/i,'retrieval interaction'],['retrieval.retriever','dual-encoder dense retriever',/dual[-\s]+encoder|dense passage retriev/i,'retriever architecture'],
 ['architecture.attention','multi-head attention',/multi[-\s]+head attention/i,'attention topology'],['architecture.attention','multi-query attention',/multi[-\s]+query attention/i,'attention topology'],['architecture.attention','sliding-window attention',/sliding[-\s]+window attention/i,'attention topology']
];
function normalized(text:string):string{return text.normalize('NFKD').replace(/[‐‑‒–—−]/g,'-').replace(/([A-Za-z])-\s+([A-Za-z])/g,'$1$2').replace(/\s+/g,' ');}
function sentence(text:string,index:number):string{const start=Math.max(text.lastIndexOf('.',index)+1,text.lastIndexOf('\n',index)+1),end=text.indexOf('.',index);return text.slice(start,end<0?text.length:end+1).trim();}
function currentWorkCue(text:string):boolean{return /\b(?:we|our|this paper|we propose|we use|we train|we report|we evaluate|the proposed)\b/i.test(text);}
function validateCandidate(candidate:CandidateEvidence):boolean{const t=candidate.rawText;const p=candidate.candidatePredicate;if(/related work|references|prior work|we compare against/i.test(t)&&!currentWorkCue(t))return false;if(p==='system.zero_stage'&&!/zero|partition|shard|stage|redundan|offload/i.test(t))return false;if(p==='reasoning.trace_type'&&!/reason|agent|chain[-\s]of[-\s]thought|trajectory|tool/i.test(t))return false;if(p==='retrieval.component'&&!/retriev|RAG|reader|passage|document/i.test(t))return false;if(p==='training.stage'&&!/train|pretrain|fine[-\s]tun|instruction|supervis|reward|policy|alignment/i.test(t))return false;if(p==='evaluation.regime'&&!/evaluat|report|accuracy|benchmark|task|prompt|learner/i.test(t))return false;if(p==='model.formulation'&&/\b(?:not|neither|without)\s+(?:be\s+)?multimodal\b/i.test(t))return false;if(p==='retrieval.component'&&/\bgenerator network\b/i.test(t)&&!/retriev|RAG|retrieved document/i.test(t))return false;return true;}
export function discoverCandidateEvidence(document:ParsedDocument):CandidateEvidence[]{const out:CandidateEvidence[]=[];for(const section of document.sections){const text=normalized(section.text);for(const [predicate,,pattern] of patterns){const match=pattern.exec(text);if(!match)continue;const rawText=sentence(section.text,match.index);out.push({candidatePredicate:predicate,rawText,sourceId:document.url,section:section.heading,context:rawText,trigger:match[0],locator:{section:section.heading,...(section.page===undefined?{}:{page:section.page}),...(section.pageId===undefined?{}:{pageId:section.pageId})}});}}return out;}
export function validateCandidateEvidence(candidates:CandidateEvidence[]):CandidateEvidence[]{return candidates.filter(validateCandidate);}
export function extractResearchFacts(document:ParsedDocument):ResearchFact[]{const facts:ResearchFact[]=[];for(const candidate of validateCandidateEvidence(discoverCandidateEvidence(document))){const rule=patterns.find(([predicate,,pattern])=>predicate===candidate.candidatePredicate&&pattern.test(candidate.trigger));if(!rule)continue;const [,value,,method,stage]=rule;const sourceClass:FactSourceClass=candidate.section.toLowerCase().includes('appendix')?'APPENDIX':'PAPER';facts.push({factId:`fact-${candidate.sourceId}-${candidate.candidatePredicate}-${value}`,predicate:candidate.candidatePredicate,value,rawValue:candidate.trigger,sourceId:candidate.sourceId,sourceClass,locator:candidate.locator,rawEvidence:candidate.rawText,...(stage?{stage}:{}),extractionMethod:method,supportState:'NORMALIZED_EXPLICIT'});}const unique=new Map<string,ResearchFact>();for(const fact of facts){const key=`${fact.predicate}:${JSON.stringify(fact.value)}:${fact.sourceId}`;if(!unique.has(key))unique.set(key,fact);}return [...unique.values()];}
export interface RepositoryFactFile { sourceId:string; path:string; commitSha:string; content:string; sourceClass?:FactSourceClass; }
export function extractRepositoryFacts(files:RepositoryFactFile[]):ResearchFact[]{const facts:ResearchFact[]=[];const patterns:Array<[string,RegExp,string]>= [['optimization.optimizer',/\b(?:optimizer\s*(?:=|:)\s*|--optimizer[= ]+)(AdamW|Adam|SGD|Adafactor|Lion)\b/i,'repository optimizer'],['optimization.learning_rate',/\b(?:learning[_ ]rate|lr)\s*(?:=|:|\s)+([0-9]+(?:\.[0-9]+)?(?:e[-+]?\d+)?)/i,'repository learning rate'],['training.batch_size',/\b(?:batch[_ ]size|per[_ ]device[_ ]train[_ ]batch[_ ]size)\s*(?:=|:|\s)+([0-9]+)/i,'repository batch size'],['training.precision',/\b(?:precision|torch[_ ]dtype)\s*(?:=|:|\s)+([A-Za-z0-9_-]+)/i,'repository precision']];for(const file of files){const lines=file.content.split(/\r?\n/);for(let index=0;index<lines.length;index++){for(const [predicate,pattern,method] of patterns){const match=pattern.exec(lines[index]!);if(!match?.[1])continue;const value=match[1];const numeric=Number(value);const canonical=Number.isFinite(numeric)?numeric:value;facts.push({factId:`repo-fact-${file.sourceId}-${file.commitSha}-${file.path}-${index+1}-${predicate}`,predicate,value:canonical,rawValue:value,sourceId:file.sourceId,sourceClass:file.sourceClass??'OTHER',locator:{repositoryPath:file.path,repositoryLineStart:index+1,repositoryLineEnd:index+1,commitSha:file.commitSha},rawEvidence:lines[index]!,extractionMethod:method,supportState:'NORMALIZED_EXPLICIT'});}}}return facts;}
