import { GitHubProvider, type GitHubContent, type GitHubDirectoryEntry } from '../providers/github.js';


export type RepositoryCandidateReason = 'README' | 'configuration' | 'training source' | 'launch script' | 'model card';
export interface RepositoryEntry { path:string; name?:string; type:string; sha?:string; }
export interface RepositoryCandidate { path:string; reason:RepositoryCandidateReason; }
export interface RepositoryFileInput { owner:string; repo:string; commitSha:string; path:string; content:string; }
export type RepositorySourceClass = 'README' | 'CONFIG' | 'TRAINING_SCRIPT' | 'MODEL_CARD' | 'OTHER';
export interface RepositoryEvidence { evidenceId:string; parameter:string; rawValue:string; normalizedValue:string|number|boolean; sourceClass:RepositorySourceClass; source:string; locator:{path:string;startLine:number;endLine:number;commitSha:string}; scope?:string; supportingText:string; }
export type InspectionState = 'INSPECTED'|'UNAVAILABLE'|'FAILED';
export type ReconciliationStatus = 'MATCH'|'PARTIAL_MATCH'|'CONFLICT'|'MISSING_IN_PAPER'|'MISSING_IN_CODE'|'NOT_REPORTED'|'UNKNOWN';
export interface ReconciliationResult { status:ReconciliationStatus; paper?:string|number|boolean; repository?:string|number|boolean; reason:string; }
export type TemporalStatus = 'ALIGNED'|'LIKELY_ALIGNED'|'PRE_PUBLICATION'|'POST_PUBLICATION'|'UNKNOWN';
export interface TemporalAlignment { status:TemporalStatus; reason:string; }
export interface StructuredAnswer { answer:string|null; status:'SUPPORTED'|'CONFLICTING'|'UNKNOWN'|'NOT_REPORTED'; evidence:RepositoryEvidence[]; conflicts:string[]; }
export interface RepositoryManifestEntry { owner:string; repo:string; commitSha:string; path:string; contentSha:string; size:number; retrievedAt:string; sourceRoute:string; }
const ignored = /^(?:vendor|node_modules|dist|build|out|checkpoints?|weights?|data|datasets?)\//i;
function basename(path:string):string { return path.split('/').at(-1) ?? path; }
function reason(path:string):RepositoryCandidateReason|undefined { const name=basename(path).toLowerCase(); if (/^readme(?:\.|$)/i.test(name)) return 'README'; if (/^(?:config|configuration|training|train|finetune)[^/]*\.(?:ya?ml|json|toml)$/i.test(name)) return 'configuration'; if (/^(?:train|training|finetune)[^/]*\.py$/i.test(name)||/(?:^|\/)(?:train|training|finetune)[^/]*\.py$/i.test(path)) return 'training source'; if (/\.(?:sh|bash)$/i.test(name)) return 'launch script'; if (/^(?:model[-_ ]?card)\.md$/i.test(name)) return 'model card'; return undefined; }
export function selectRepositoryCandidates(entries:RepositoryEntry[], limit=30):RepositoryCandidate[] { if(!Number.isInteger(limit)||limit<1)throw new Error('limit must be a positive integer'); const selected=entries.filter(entry=>entry.type==='file'&&!ignored.test(entry.path)).map(entry=>({path:entry.path,reason:reason(entry.path)})).filter((x):x is RepositoryCandidate=>Boolean(x.reason)); const priority:Record<RepositoryCandidateReason,number>={README:0,configuration:1,'launch script':2,'training source':3,'model card':4}; return selected.sort((a,b)=>priority[a.reason]-priority[b.reason]||a.path.localeCompare(b.path)).slice(0,limit); }
function sourceClass(path:string):RepositorySourceClass { const name=basename(path).toLowerCase(); if(/^readme(?:\.|$)/.test(name))return 'README'; if(/^model[-_ ]?card\.md$/.test(name))return 'MODEL_CARD'; if(/\.(?:ya?ml|json|toml)$/.test(name))return 'CONFIG'; if(/\.(?:py|sh|bash)$/.test(name))return 'TRAINING_SCRIPT'; return 'OTHER'; }
const patterns:Array<[string,RegExp]>=[['learning_rate',/(?:learning[_ ]rate|lr)\s*(?:=|:|of)?\s*([0-9]+(?:\.[0-9]+)?(?:e[-+]?\d+)?)/i],['batch_size',/batch[_ ]size\s*(?:=|:|of)?\s*(\d+)/i],['epochs',/epochs?\s*(?:=|:|of)?\s*(\d+)/i],['optimizer',/optimizer\s*(?:=|:|of)?\s*([A-Za-z][A-Za-z0-9_-]*)/i],['weight_decay',/weight[_ ]decay\s*(?:=|:|of)?\s*([0-9]+(?:\.[0-9]+)?(?:e[-+]?\d+)?)/i],['gradient_accumulation',/gradient[_ ]accumulation(?:[_ ]steps?)?\s*(?:=|:|of)?\s*(\d+)/i]];
function normalize(raw:string):string|number|boolean { const n=Number(raw); return raw!==''&&Number.isFinite(n)?n:raw.toLowerCase()==='true'?true:raw.toLowerCase()==='false'?false:raw; }
export function extractRepositoryEvidence(input:RepositoryFileInput):RepositoryEvidence[] { if(!/^[0-9a-f]{40}$/i.test(input.commitSha))throw new Error('commitSha must be a 40-character SHA'); const lines=input.content.split(/\r?\n/); const out:RepositoryEvidence[]=[]; const source=sourceClass(input.path); for(const [parameter,pattern] of patterns)for(let i=0;i<lines.length;i++){const match=lines[i]!.match(pattern);if(!match?.[1])continue;const raw=match[1];out.push({evidenceId:`repo-${input.owner}-${input.repo}-${input.commitSha}-${input.path}-${i+1}-${parameter}`,parameter,rawValue:raw,normalizedValue:normalize(raw),sourceClass:source,source:`https://github.com/${input.owner}/${input.repo}`,locator:{path:input.path,startLine:i+1,endLine:i+1,commitSha:input.commitSha},supportingText:lines[i]!});} return out; }
function equal(a:string|number,b:string|number|boolean):boolean { return typeof a==='number'&&typeof b==='number'?a===b:String(a).trim().toLowerCase()===String(b).trim().toLowerCase(); }
export function reconcileEvidence(input:{paper?:Array<{parameter:string;value:string|number}>;repository?:RepositoryEvidence[];paperInspection:InspectionState;repositoryInspection:InspectionState},parameter?:string):ReconciliationResult { if(input.paperInspection!=='INSPECTED'||input.repositoryInspection!=='INSPECTED')return{status:'UNKNOWN',reason:'authoritative source inspection was unavailable or failed'};const paper=input.paper?.find(x=>!parameter||x.parameter===parameter);const repo=input.repository?.find(x=>!parameter||x.parameter===parameter);if(paper&&repo)return equal(paper.value,repo.normalizedValue)?{status:'MATCH',paper:paper.value,repository:repo.normalizedValue,reason:'normalized values and requested scope agree'}:{status:'CONFLICT',paper:paper.value,repository:repo.normalizedValue,reason:'inspected paper and repository values differ'};if(paper)return{status:'MISSING_IN_CODE',paper:paper.value,reason:'repository was inspected but no matching evidence was found'};if(repo)return{status:'MISSING_IN_PAPER',repository:repo.normalizedValue,reason:'paper was inspected but no matching evidence was found'};return{status:'NOT_REPORTED',reason:'both authoritative sources were inspected and no matching evidence was found'}; }
export function classifyTemporalAlignment(publicationDate?:string,commitDate?:string):TemporalAlignment { if(!publicationDate||!commitDate)return{status:'UNKNOWN',reason:'publication or commit date is unavailable'};const p=Date.parse(publicationDate),c=Date.parse(commitDate);if(!Number.isFinite(p)||!Number.isFinite(c))return{status:'UNKNOWN',reason:'publication or commit date is invalid'};if(c<p)return{status:'PRE_PUBLICATION',reason:'pinned commit predates publication'};const days=(c-p)/86400000;if(days<=30)return{status:'LIKELY_ALIGNED',reason:'pinned commit follows publication within 30 days; exact alignment is not proven'};return{status:'POST_PUBLICATION',reason:'pinned commit is materially later than publication'}; }
export function assembleStructuredAnswer(parameter:string,repository:RepositoryEvidence[],conflicts:string[]):StructuredAnswer { const matches=repository.filter(item=>item.parameter===parameter);if(conflicts.length)return{answer:null,status:'CONFLICTING',evidence:matches,conflicts};if(matches.length===1)return{answer:String(matches[0]!.normalizedValue),status:'SUPPORTED',evidence:matches,conflicts:[]};return{answer:null,status:'UNKNOWN',evidence:[],conflicts:[]}; }

export class PinnedRepositoryReader {
  constructor(private readonly github:Pick<GitHubProvider,'listContents'|'getContent'>=new GitHubProvider(), private readonly maxFiles=30, private readonly maxBytes=256_000) {}
  async read(owner:string,repo:string,commitSha:string):Promise<{evidence:RepositoryEvidence[];manifest:RepositoryManifestEntry[];failures:string[]}> {
    if(!/^[0-9a-f]{40}$/i.test(commitSha))throw new Error('commitSha must be a 40-character SHA');
    const root=await this.github.listContents(owner,repo,'',commitSha); const candidates=selectRepositoryCandidates(root as GitHubDirectoryEntry[],this.maxFiles); const evidence:RepositoryEvidence[]=[]; const manifest:RepositoryManifestEntry[]=[]; const failures:string[]=[];
    for(const candidate of candidates){ try { const file=await this.github.getContent(owner,repo,candidate.path,commitSha) as GitHubContent|undefined; const content=file ? (file.content && file.encoding==='base64' ? Buffer.from(file.content.replaceAll('\n',''),'base64').toString('utf8') : file.content) : undefined; if(!content||content.length>this.maxBytes){failures.push(`${candidate.path}: unavailable or exceeds byte limit`);continue;} evidence.push(...extractRepositoryEvidence({owner,repo,commitSha,path:candidate.path,content})); manifest.push({owner,repo,commitSha,path:candidate.path,contentSha:file?.sha??'',size:Buffer.byteLength(content),retrievedAt:new Date().toISOString(),sourceRoute:`github:contents/${owner}/${repo}@${commitSha}`}); } catch(error){failures.push(`${candidate.path}: ${String(error)}`);} }
    return {evidence,manifest,failures};
  }
}

