import { createHash } from 'node:crypto';
import type { GitHubDirectoryEntry, GitHubContent } from '../providers/github.js';

export type FileReason = 'README'|'configuration'|'training source'|'launch script'|'model card';
export interface RepositoryFileCandidate { path:string; reason:FileReason; }
export interface PinnedRepositoryInput { owner:string; repo:string; commitSha:string; path:string; content:string; }
export type RepositorySourceClass = 'README'|'CONFIG'|'TRAINING_SCRIPT'|'MODEL_CARD'|'OTHER';
export interface RepositoryEvidence { evidenceId:string; parameter:string; rawValue:string; normalizedValue:string|number; sourceClass:RepositorySourceClass; sourceId:string; supportingText:string; locator:{path:string;startLine:number;endLine:number;commitSha:string}; }
export interface RepositoryManifestEntry { owner:string; repo:string; commitSha:string; path:string; contentSha256:string; bytes:number; sourceRoute:string; }
export type InspectionState = 'INSPECTED'|'UNAVAILABLE'|'FAILED';
export interface RealEvidenceReconciliation { status:'MATCH'|'CONFLICT'|'MISSING_IN_PAPER'|'MISSING_IN_CODE'|'NOT_REPORTED'|'UNKNOWN'; reason:string; paperValue?:string|number; repositoryValue?:string|number; }

const ignored=/^(?:vendor|node_modules|dist|build|out|checkpoints?|weights?|data|datasets?)\//i;
const filename=(path:string)=>path.split('/').at(-1) ?? path;
function fileReason(path:string):FileReason|undefined { const name=filename(path).toLowerCase(); if(/^readme(?:\.|$)/i.test(name))return 'README'; if(/^(?:config|configuration|training|train|finetune)[^/]*\.(?:ya?ml|json|toml)$/i.test(name))return 'configuration'; if(/(?:^|\/)(?:train|training|finetune)[^/]*\.py$/i.test(path))return 'training source'; if(/\.(?:sh|bash)$/i.test(name))return 'launch script'; if(/^model[-_ ]?card\.md$/i.test(name))return 'model card'; return undefined; }
export function selectRepositoryFiles(entries:Pick<GitHubDirectoryEntry,'path'|'name'|'type'>[],limit=30):RepositoryFileCandidate[] { if(!Number.isInteger(limit)||limit<1)throw new Error('limit must be a positive integer'); const priority:Record<FileReason,number>={README:0,configuration:1,'launch script':2,'training source':3,'model card':4}; return entries.filter(entry=>entry.type==='file'&&!ignored.test(entry.path)).map(entry=>({path:entry.path,reason:fileReason(entry.path)})).filter((entry):entry is RepositoryFileCandidate=>Boolean(entry.reason)).sort((a,b)=>priority[a.reason]-priority[b.reason]||a.path.localeCompare(b.path)).slice(0,limit); }
const patterns:Array<[string,RegExp]>=[['learning_rate',/(?:learning[_ ]rate|lr)\s*(?:=|:|of)?\s*([0-9]+(?:\.[0-9]+)?(?:e[-+]?\d+)?)/i],['batch_size',/batch[_ ]size\s*(?:=|:|of)?\s*(\d+)/i],['epochs',/epochs?\s*(?:=|:|of)?\s*(\d+)/i],['optimizer',/optimizer\s*(?:=|:|of)?\s*([A-Za-z][A-Za-z0-9_-]*)/i],['weight_decay',/weight[_ ]decay\s*(?:=|:|of)?\s*([0-9]+(?:\.[0-9]+)?(?:e[-+]?\d+)?)/i],['gradient_accumulation',/gradient[_ ]accumulation(?:[_ ]steps?)?\s*(?:=|:|of)?\s*(\d+)/i]];
const normalize=(raw:string):string|number=>Number.isFinite(Number(raw))?Number(raw):raw;
function sourceClass(path:string):RepositorySourceClass { const name=filename(path).toLowerCase(); if(/^readme(?:\.|$)/.test(name))return 'README'; if(/^model[-_ ]?card\.md$/.test(name))return 'MODEL_CARD'; if(/\.(?:ya?ml|json|toml)$/.test(name))return 'CONFIG'; if(/\.(?:py|sh|bash)$/.test(name))return 'TRAINING_SCRIPT'; return 'OTHER'; }
export function extractPinnedRepositoryEvidence(input:PinnedRepositoryInput):RepositoryEvidence[] { if(!/^[0-9a-f]{40}$/i.test(input.commitSha))throw new Error('commitSha must be a 40-character SHA'); const lines=input.content.split(/\r?\n/); const output:RepositoryEvidence[]=[]; for(const [parameter,pattern] of patterns)for(let index=0;index<lines.length;index++){const match=lines[index]!.match(pattern);if(!match?.[1])continue;const rawValue=match[1];output.push({evidenceId:`repo-${input.owner}-${input.repo}-${input.commitSha}-${input.path}-${index+1}-${parameter}`,parameter,rawValue,normalizedValue:normalize(rawValue),sourceClass:sourceClass(input.path),sourceId:`https://github.com/${input.owner}/${input.repo}`,supportingText:lines[index]!,locator:{path:input.path,startLine:index+1,endLine:index+1,commitSha:input.commitSha}});} return output; }
export function manifestEntry(input:PinnedRepositoryInput):RepositoryManifestEntry { return {owner:input.owner,repo:input.repo,commitSha:input.commitSha,path:input.path,contentSha256:createHash('sha256').update(input.content).digest('hex'),bytes:Buffer.byteLength(input.content),sourceRoute:`github:contents/${input.owner}/${input.repo}@${input.commitSha}`}; }
export function reconcileRealEvidence(input:{paperInspection:InspectionState;repositoryInspection:InspectionState;paper:Array<{parameter:string;value:string|number}>;repository:RepositoryEvidence[]},parameter?:string):RealEvidenceReconciliation { if(input.paperInspection!=='INSPECTED'||input.repositoryInspection!=='INSPECTED')return{status:'UNKNOWN',reason:'source acquisition or parsing did not complete'}; const paper=input.paper.find(item=>!parameter||item.parameter===parameter); const repository=input.repository.find(item=>!parameter||item.parameter===parameter); if(paper&&repository){const equal=typeof paper.value==='number'&&typeof repository.normalizedValue==='number'?paper.value===repository.normalizedValue:String(paper.value).trim().toLowerCase()===String(repository.normalizedValue).trim().toLowerCase();return equal?{status:'MATCH',paperValue:paper.value,repositoryValue:repository.normalizedValue,reason:'normalized values agree'}:{status:'CONFLICT',paperValue:paper.value,repositoryValue:repository.normalizedValue,reason:'inspected source values differ'};} if(paper)return{status:'MISSING_IN_CODE',paperValue:paper.value,reason:'repository was inspected without matching evidence'}; if(repository)return{status:'MISSING_IN_PAPER',repositoryValue:repository.normalizedValue,reason:'paper was inspected without matching evidence'}; return{status:'NOT_REPORTED',reason:'both requested source scopes were inspected without matching evidence'}; }
export type PinnedContent = Pick<GitHubContent,'path'|'sha'|'content'|'encoding'>;
