import type { ResearchWork, Evidence, ResearchResponse, TrainingRecipe, Reported, GraphItem, GraphRelation, AuthorProfile, GraphEdge, SourceConflict, RelationshipClass, RelationshipBasis } from '../models/research.js';
import { ResearchDb } from '../database/db.js';
import type { ResearchStore } from '../database/store.js';
import { ArxivProvider } from '../providers/arxiv.js';
import { CrossrefProvider } from '../providers/crossref.js';
import { OpenAlexProvider } from '../providers/openalex.js';
import { SemanticScholarProvider } from '../providers/semantic-scholar.js';
import { makeEvidence, normalizeAuthorName } from './citations.js';
import { getReliabilityStats } from '../reliability/reliability.js';
import { PaperAcquirer } from '../ingestion/acquisition.js';
import { createHash } from 'node:crypto';
import { parseDocument, detectDocumentFormat, searchDocument } from '../ingestion/document.js';
import { PdfParserChain, GrobidClient, createConfiguredPdfFallbacks } from '../ingestion/pdf.js';
import { extractPaperFacts, type PaperFact } from '../extraction/heuristic.js';
import { extractPaperClaims, reconcileClaims, type PaperClaim, type ClaimConflict } from '../extraction/claims.js';
import { extractTrainingParameters, type TrainingParameter } from '../extraction/parameters.js';
import type { Collection } from '../database/db.js';
import type { PaperExtractor } from '../extraction/extractor.js';
import type { ConfigField } from './config-extraction.js';
import { compareRecipeToConfig, type ReproducibilityComparison } from './reproducibility.js';
import type { ResearchPack } from './research-pack.js';

const missing = <T>(): Reported<T> => ({ value: null, status: 'NOT_REPORTED' });
export interface SearchFilters { yearFrom?: number; yearTo?: number; author?: string; venue?: string; topic?: string; }
export interface RefreshOutcome { paperId:string; status:'REFRESHED'|'UNAVAILABLE'|'FAILED'; provider?:string; error?:string; }
export interface ResearchReport { query:string; mode:'literature_review'|'implementation'|'reproducibility'; facts:string[]; recommendations:string[]; timeline:Array<{paperId:string;year:number;title:string}>; }
export interface MethodComparison { methods: [string, string]; leftResults: ResearchWork[]; rightResults: ResearchWork[]; overlap: string[]; benchmarkComparability:'COMPARABLE'|'NOT_COMPARABLE'|'UNKNOWN'; }
export interface PaperComparison { paperIds: [string, string]; differences: Array<{field:string; left:string|null; right:string|null}>; benchmarkComparability:'COMPARABLE'|'NOT_COMPARABLE'|'UNKNOWN'; }
export class ResearchService {
  constructor(public readonly db:ResearchStore = new ResearchDb(), private readonly arxiv = new ArxivProvider(), private readonly crossref = new CrossrefProvider(), private readonly openalex = new OpenAlexProvider(), private readonly semanticScholar = new SemanticScholarProvider(), private readonly acquirer = new PaperAcquirer(), private readonly pdfParser = new PdfParserChain(new GrobidClient(), createConfiguredPdfFallbacks())) {}
  async flushStorage():Promise<void> { const flush=(this.db as ResearchStore & {flush?:()=>Promise<void>}).flush; if(flush) await flush(); }
  createCollection(name:string):Collection { return this.db.createCollection(name); }
  listCollections():Collection[] { return this.db.listCollections(); }
  addToCollection(collectionId:string,paperId:string):void { if(!this.db.getCollection(collectionId)) throw new Error('NOT_FOUND: collection does not exist'); if(!this.db.getWork(paperId)) throw new Error('NOT_FOUND: paper does not exist'); this.db.addToCollection(collectionId,paperId); }
  removeFromCollection(collectionId:string,paperId:string):void { if(!this.db.getCollection(collectionId)) throw new Error('NOT_FOUND: collection does not exist'); this.db.removeFromCollection(collectionId,paperId); }
  deleteCollection(collectionId:string):void { if(!this.db.getCollection(collectionId)) throw new Error('NOT_FOUND: collection does not exist'); this.db.deleteCollection(collectionId); }
  getCollection(collectionId:string):Collection|undefined { return this.db.getCollection(collectionId); }
  async refreshPaper(paperId:string):Promise<RefreshOutcome> { const paper=this.db.getWork(paperId); if(!paper) throw new Error('NOT_FOUND: paper does not exist'); if(!paper.semanticScholarId) return {paperId,status:'UNAVAILABLE',error:'no provider-native refresh identifier'}; try { const refreshed=await this.semanticScholar.getPaper(paper.semanticScholarId); if(!refreshed) return {paperId,status:'UNAVAILABLE',provider:'semantic_scholar',error:'provider returned no paper'}; this.db.upsertWork(refreshed); return {paperId,status:'REFRESHED',provider:'semantic_scholar'}; } catch(error) { return {paperId,status:'FAILED',provider:'semantic_scholar',error:String(error)}; } }
  async refreshCollection(collectionId:string):Promise<RefreshOutcome[]> { const collection=this.db.getCollection(collectionId); if(!collection) throw new Error('NOT_FOUND: collection does not exist'); return Promise.all(collection.paperIds.map(paperId=>this.refreshPaper(paperId))); }
  importResearchPack(pack:ResearchPack):Collection { if(pack.format!=='openpapers.research-pack.v1') throw new Error('unsupported ResearchPack format'); if(!pack.collection || typeof pack.collection.name!=='string' || !Array.isArray(pack.papers) || !Array.isArray(pack.evidence)) throw new Error('invalid ResearchPack structure'); const collection=this.db.createCollection(pack.collection.name); for(const paper of pack.papers) { if(!paper || typeof paper.paperId!=='string' || typeof paper.title!=='string' || !Array.isArray(paper.authors) || typeof paper.bibtex!=='string' || !Array.isArray(paper.sourceProviders) || !Array.isArray(paper.versions)) throw new Error('invalid ResearchPack paper'); this.db.upsertWork(paper); this.db.addToCollection(collection.id,paper.paperId); } for(const item of pack.evidence) { if(!item || typeof item.paperId!=='string' || !item.evidence) throw new Error('invalid ResearchPack evidence'); this.db.addEvidence(item.evidence,item.paperId); } return this.db.getCollection(collection.id)!; }
  buildResearchPack(collectionId:string):ResearchPack { const collection=this.db.getCollection(collectionId); if(!collection) throw new Error('NOT_FOUND: collection does not exist'); const papers=collection.paperIds.map(id=>this.db.getWork(id)).filter((paper):paper is ResearchWork=>Boolean(paper)); const evidence=papers.flatMap(paper=>this.db.getEvidenceForPaper(paper.paperId).map(evidence=>({paperId:paper.paperId,evidence}))); return {format:'openpapers.research-pack.v1',collection:{id:collection.id,name:collection.name},papers,evidence}; }
  async search(query: string, limit = 10, filters: SearchFilters = {}): Promise<ResearchResponse<ResearchWork[]>> { const expandedQueries = expand(query); const settled = await Promise.allSettled([this.arxiv.search(expandedQueries[0] ?? query, limit), this.crossref.search(query, limit), this.openalex.search(query, limit), this.semanticScholar.search(query, limit)]); const works = new Map<string, ResearchWork>(); const conflicts:SourceConflict[]=[]; for (const result of settled) if (result.status === 'fulfilled') for (const work of result.value) { const key = canonicalKey(work); const existing = works.get(key); if (existing) { collectConflicts(existing,work,conflicts); existing.sourceProviders = [...new Set([...existing.sourceProviders, ...work.sourceProviders])]; existing.versions.push(...work.versions); if (existing.doi === undefined && work.doi !== undefined) existing.doi = work.doi; if (existing.arxivId === undefined && work.arxivId !== undefined) existing.arxivId = work.arxivId; if (existing.semanticScholarId === undefined && work.semanticScholarId !== undefined) existing.semanticScholarId = work.semanticScholarId; if (existing.openAlexId === undefined && work.openAlexId !== undefined) existing.openAlexId = work.openAlexId; existing.citationCount = Math.max(existing.citationCount ?? 0, work.citationCount ?? 0); this.db.upsertWork(existing); } else { works.set(key, work); this.db.upsertWork(work); } } const ranked = [...works.values()].filter(work => matchesFilters(work, filters)).sort((a,b) => score(b, query)-score(a, query)).slice(0, limit); const evidence = ranked.map(w => makeEvidence(w.paperId, w, `Metadata identifies the work as “${w.title}”.`, 'DIRECT', 'C')); return { summary: ranked.length ? ranked.map(w => `${w.authors[0]?.name ?? 'Unknown'} et al. — ${w.title} ${w.year ? `(${w.year})` : ''} ${w.canonicalUrl ?? ''} ${evidence.find(e => e.sourceId === w.paperId)?.citationText ?? ''}`).join('\n') : 'No verified works were retrieved.', data: ranked, evidence, references: ranked, transparency: { query, expandedQueries, sourcesSearched: ['arxiv','crossref','openalex','semantic_scholar'], providerFailures: settled.map((result, index) => result.status === 'rejected' ? `${['arxiv','crossref','openalex','semantic_scholar'][index]}: ${String(result.reason)}` : undefined).filter((failure): failure is string => Boolean(failure)), reliability: getReliabilityStats(), candidates: works.size, retrievedAt: new Date().toISOString(), rankingRationale: ['lexical relevance', 'source availability', 'recency'], conflicts } }; }
  async verifyClaim(claimId: string): Promise<ResearchResponse<{claim:PaperClaim;status:'UNKNOWN'|'SUPPORTED'|'CONTRADICTED';conflicts:ClaimConflict[]}>> { const claim=this.db.getClaim(claimId); if(!claim) throw new Error('NOT_FOUND: claim is not in the local verified database'); const conflicts=this.db.getClaimConflicts().filter(conflict=>conflict.selectedClaimId===claimId||conflict.alternateClaimId===claimId); const status=conflicts.length ? 'CONTRADICTED' as const : 'UNKNOWN' as const; const relatedEvidence=conflicts.flatMap(conflict=>[this.db.getClaim(conflict.selectedClaimId)?.evidence,this.db.getClaim(conflict.alternateClaimId)?.evidence]).filter((e): e is PaperClaim['evidence']=>Boolean(e)); const evidence=[...new Map([claim.evidence,...relatedEvidence].map(item=>[item.evidenceId,item])).values()]; return {summary:`Claim verification is ${status}: ${conflicts.length ? `${conflicts.length} persisted conflicting claim record(s) were found.` : 'no independent verification source is attached.'} ${evidence.map(item=>item.citationText).join(' ')}`,data:{claim,status,conflicts},evidence,references:[],transparency:{expandedQueries:[],sourcesSearched:['local claim store'],candidates:1+conflicts.length,retrievedAt:new Date().toISOString(),rankingRationale:['persisted claim conflict status','independent verification remains unavailable']}}; }
  async buildResearchReport(query:string, mode:'literature_review'|'implementation'|'reproducibility'='literature_review', limit=15):Promise<ResearchResponse<ResearchReport>> { const response=await this.search(query,limit); const facts=response.data.map(work=>`${work.authors[0]?.name ?? 'Unknown'} et al. — ${work.title}${work.year ? ` (${work.year})` : ''} ${response.evidence.find(item=>item.sourceId===work.paperId)?.citationText ?? ''}`); const recommendations=mode==='implementation' ? ['Inspect linked repositories with find_implementations before treating any code as official.'] : mode==='reproducibility' ? ['Extract explicit training parameters and compare them with revision-pinned repository configuration.'] : ['Review the cited papers and verify claims before making implementation decisions.']; const timeline=response.data.filter((work):work is ResearchWork & {year:number}=>work.year!==undefined).map(work=>({paperId:work.paperId,year:work.year,title:work.title})).sort((a,b)=>a.year-b.year||a.paperId.localeCompare(b.paperId)); const data={query,mode,facts,recommendations,timeline}; return {...response,data,summary:`${response.summary}\nRecommendations (${mode}): ${recommendations.join(' ')}`}; }
  async compareMethods(leftMethod: string, rightMethod: string, limit = 10): Promise<ResearchResponse<MethodComparison>> { const [left,right]=await Promise.all([this.search(leftMethod,limit),this.search(rightMethod,limit)]); const rightIds=new Set(right.data.map(work=>comparisonKey(work))); const overlap=left.data.filter(work=>rightIds.has(comparisonKey(work))).map(work=>work.paperId); const references=[...new Map([...left.references,...right.references].map(work=>[work.paperId,work])).values()]; const evidence=[...new Map([...left.evidence,...right.evidence].map(item=>[item.evidenceId,item])).values()]; return {summary:`Compared method searches “${leftMethod}” and “${rightMethod}”; ${overlap.length} verified result overlap(s). Benchmark comparability is UNKNOWN without aligned benchmark evidence. ${evidence.map(item=>item.citationText).join(' ')}`,data:{methods:[leftMethod,rightMethod],leftResults:left.data,rightResults:right.data,overlap,benchmarkComparability:'UNKNOWN'},evidence,references,transparency:{expandedQueries:[...left.transparency.expandedQueries,...right.transparency.expandedQueries],sourcesSearched:[...new Set([...left.transparency.sourcesSearched,...right.transparency.sourcesSearched])],providerFailures:[...(left.transparency.providerFailures ?? []),...(right.transparency.providerFailures ?? [])],candidates:left.transparency.candidates+right.transparency.candidates,retrievedAt:new Date().toISOString(),rankingRationale:['independent bounded method searches','paper ID overlap']}}; }
  async comparePapers(leftId: string, rightId: string): Promise<ResearchResponse<PaperComparison>> { const left=this.db.getWork(leftId); const right=this.db.getWork(rightId); if(!left||!right) throw new Error(`NOT_FOUND: both papers must exist in the local verified database`); const fields:Array<keyof ResearchWork>=['title','year','venue','doi','arxivId']; const differences=fields.map(field=>({field,left:left[field] === undefined ? null : String(left[field]),right:right[field] === undefined ? null : String(right[field])})).filter(item=>item.left!==item.right); const evidence=[makeEvidence(left.paperId,left,`Metadata used for comparison of ${left.title}.`,'DIRECT','C'),makeEvidence(right.paperId,right,`Metadata used for comparison of ${right.title}.`,'DIRECT','C')]; return {summary:`Compared ${left.title} and ${right.title}. Benchmark comparability is UNKNOWN without aligned benchmark evidence. ${evidence.map(item=>item.citationText).join(' ')}`,data:{paperIds:[left.paperId,right.paperId],differences,benchmarkComparability:'UNKNOWN'},evidence,references:[left,right],transparency:{expandedQueries:[],sourcesSearched:['local database'],candidates:2,retrievedAt:new Date().toISOString(),rankingRationale:['explicit canonical metadata comparison']}}; }
  async researchMethod(method: string, limit = 10): Promise<ResearchResponse<ResearchWork[]>> { const response = await this.search(method, limit); return {...response, summary:`Research results for method “${method}”: ${response.summary}`}; }
  async graphAll(id:string, relation:GraphRelation, limit=20):Promise<ResearchResponse<GraphItem[]>> {
    const semanticCall = relation === 'reference' ? this.semanticScholar.getReferences(id, limit) : relation === 'citation' ? this.semanticScholar.getCitations(id, limit) : this.semanticScholar.getRelated(id, limit);
    const root = this.db.getWork(id);
    const openAlexId = root?.openAlexId ?? (id.startsWith('https://openalex.org/') ? id : undefined);
    const openAlexCall = openAlexId ? (relation === 'reference' ? this.openalex.getReferences(openAlexId, limit) : relation === 'citation' ? this.openalex.getCitations(openAlexId, limit) : Promise.resolve([])) : Promise.resolve([]);
    const settled = await Promise.allSettled([semanticCall, openAlexCall]);
    const candidates = settled.flatMap((result, index) => result.status === 'fulfilled' ? result.value.map(work => ({work, source: index === 0 ? 'semantic_scholar' : 'openalex'})) : []);
    const failures = settled.map((result, index) => result.status === 'rejected' ? `${index === 0 ? 'semantic_scholar' : 'openalex'}: ${String(result.reason)}` : undefined).filter((failure): failure is string => Boolean(failure));
    const conflicts:SourceConflict[] = [];
    const unique = new Map<string, {work:ResearchWork; source:string; providers:string[]}>();
    for (const candidate of candidates) {
      const work = resolveGraphWork(this.db, candidate.work);
      const key = work.doi ?? work.arxivId ?? canonicalKey(work);
      const existing = unique.get(key);
      if (existing) {
        collectConflicts(existing.work, work, conflicts);
        existing.work.sourceProviders = [...new Set([...existing.work.sourceProviders, ...work.sourceProviders])];
        existing.source = `${existing.source},${candidate.source}`;
        existing.providers = [...new Set([...existing.providers, candidate.source])];
      } else unique.set(key, {work, source:candidate.source, providers:[candidate.source]});
    }
    const items = [...unique.values()].slice(0, limit);
    const retrievedAt = new Date().toISOString();
    const evidence = items.map(item => makeEvidence(item.work.paperId, item.work, `${item.source} reports this work as a ${relation} of ${id}.`, 'DIRECT', item.providers.includes('semantic_scholar') ? 'B' : 'C'));
    const data = items.map((item, index) => ({work:item.work, relation, relationshipClass:classifyGraphRelationship(root, item.work, relation, {explicitRelation:relation}), relationshipBasis:(relation === 'related' ? 'UNKNOWN' : 'PROVIDER_EXPLICIT') as RelationshipBasis, source:item.source, evidence:evidence[index]!}));
    data.forEach((item, index) => {
      this.db.upsertWork(item.work);
      this.db.addEvidence(item.evidence, item.work.paperId);
      for (const provider of items[index]!.providers) this.db.upsertGraphEdge({sourcePaperId:id, targetPaperId:item.work.paperId, relation, provider, relationshipClass:item.relationshipClass, evidenceId:evidence[index]!.evidenceId, retrievedAt});
    });
    return {summary:data.length ? data.map(item => `${item.work.title} ${item.evidence.citationText}`).join('\n') : `No ${relation} works were reported.`, data, evidence, references:items.map(item => item.work), transparency:{expandedQueries:[], sourcesSearched:openAlexId ? ['semantic_scholar','openalex'] : ['semantic_scholar'], providerFailures:failures, candidates:candidates.length, retrievedAt, rankingRationale:['identifier-first cross-provider graph reconciliation'], conflicts}};
  }
  async graph(id:string, relation:GraphRelation, limit=20):Promise<ResearchResponse<GraphItem[]>> { const works=relation==='reference'?await this.semanticScholar.getReferences(id,limit):relation==='citation'?await this.semanticScholar.getCitations(id,limit):await this.semanticScholar.getRelated(id,limit); const root=this.db.getWork(id); const resolvedWorks=works.map(work=>resolveGraphWork(this.db,work)); const retrievedAt=new Date().toISOString(); const evidence=resolvedWorks.map(work=>makeEvidence(work.paperId,work,`Semantic Scholar reports this work as a ${relation} of ${id}.`,'DIRECT','B')); const data=resolvedWorks.map((work,index)=>({work,relation,relationshipClass:classifyGraphRelationship(root,work,relation,{explicitRelation:relation}),relationshipBasis:(relation === 'related' ? 'UNKNOWN' : 'PROVIDER_EXPLICIT') as RelationshipBasis,source:'semantic_scholar',evidence:evidence[index]!})); data.forEach((item,index)=>{ this.db.upsertWork(item.work); this.db.addEvidence(item.evidence,item.work.paperId); const edge:GraphEdge={sourcePaperId:id,targetPaperId:item.work.paperId,relation,provider:item.source,relationshipClass:item.relationshipClass,evidenceId:evidence[index]!.evidenceId,retrievedAt}; this.db.upsertGraphEdge(edge); }); return {summary:data.length?data.map(item=>`${item.work.title} ${item.evidence.citationText}`).join('\\n'):`No ${relation} works were reported.`,data,evidence,references:resolvedWorks,transparency:{expandedQueries:[],sourcesSearched:['semantic_scholar'],providerFailures:[],candidates:data.length,retrievedAt,rankingRationale:[`Semantic Scholar ${relation} graph response`]}}; }
  async resolveAuthor(id:string):Promise<AuthorProfile|undefined> { const profile=await this.semanticScholar.resolveAuthor(id); return profile?.authorId&&profile.name ? {authorId:profile.authorId,name:profile.name,aliases:profile.aliases ?? [],paperIds:(profile.papers ?? []).map(paper=>paper.paperId).filter((paperId):paperId is string=>Boolean(paperId)),source:'semantic_scholar'} : undefined; }
  async readPaper(url:string) { const acquired=await this.acquirer.acquire(url); const hash=createHash('sha256').update(acquired.body).digest('hex'); const cached=this.db.getParsedDocument(acquired.url,hash); if(cached)return cached; const parsed=detectDocumentFormat(acquired.contentType,acquired.body)==='pdf' ? await this.pdfParser.process(acquired.body,acquired.url) : parseDocument(acquired); this.db.saveParsedDocument(parsed,hash); return parsed; }
  async searchWithinPaper(url:string, query:string, limit=10) { return searchDocument(await this.readPaper(url), query, limit); }
  async extractPaperFacts(url:string): Promise<PaperFact[]> { return extractPaperFacts(await this.readPaper(url)); }
  async extractPaperClaims(url:string): Promise<{claims:PaperClaim[]; conflicts:ClaimConflict[]}> { const claims=extractPaperClaims(await this.extractPaperFacts(url)); const reconciliation=reconcileClaims(this.db.getClaims(),claims); claims.forEach(claim=>this.db.saveClaim(claim)); reconciliation.conflicts.forEach(conflict=>this.db.saveClaimConflict(conflict)); return {claims,conflicts:reconciliation.conflicts}; }
  async extractTrainingParameters(url:string): Promise<TrainingParameter[]> { return extractTrainingParameters(await this.readPaper(url)); }
  async recipeFromPaper(url:string): Promise<ResearchResponse<TrainingRecipe>> { const document=await this.readPaper(url); const parameters=extractTrainingParameters(document); const facts=extractPaperFacts(document); const base=this.recipe({paperId:url,title:url,authors:[],publicationStatus:'unknown',bibtex:'',sourceProviders:['paper'],versions:[]}); const valueFor=<T>(name:TrainingParameter['name'],convert:(value:string)=>T):Reported<T>=>{ const parameter=parameters.find(item=>item.name===name); return parameter ? {value:convert(parameter.value),status:'REPORTED',sources:[parameter.sourceUrl]} : missing<T>(); }; const factsFor=(kind:PaperFact['kind'])=>facts.filter(fact=>fact.kind===kind); const reportedFacts=(kind:PaperFact['kind']):Reported<string[]>=>{ const selected=factsFor(kind); return selected.length ? {value:selected.map(fact=>fact.text),status:'REPORTED',sources:[...new Set(selected.map(fact=>fact.sourceUrl))]} : missing<string[]>(); }; const method=factsFor('methodology')[0]?.text ?? 'unknown'; const sources=[...base.data.sources,...facts.map((fact,index)=>({evidenceId:`recipe-fact-${index}`,sourceId:fact.sourceUrl,authors:[],title:`Extracted ${fact.kind} fact`,identifiers:{},locator:fact.locator,evidenceType:'DERIVED' as const,sourceQuality:'C' as const,evidence:fact.text,citationText:`${fact.sourceUrl}${fact.locator.section ? `#${fact.locator.section}` : ''}`}))]; return {...base,data:{...base.data,method,objectives:reportedFacts('loss'),losses:reportedFacts('loss'),datasets:reportedFacts('dataset'),learning_rate:valueFor('learning_rate',Number),batch_size:valueFor('batch_size',Number),epochs:valueFor('epochs',Number),weight_decay:valueFor('weight_decay',Number),temperature:valueFor('temperature',Number),gradient_accumulation:valueFor('gradient_accumulation',Number),optimizer:{name:valueFor('optimizer',String)},sources},evidence:sources,summary:`Training recipe extracted from ${url}; heuristic facts and explicit parameters retain their source locators, and absent fields remain NOT_REPORTED.`}; }
  compareRecipeToConfig(recipe:TrainingRecipe, fields:ConfigField[], source:{url:string;commitSha?:string}):ReproducibilityComparison { return compareRecipeToConfig(recipe,fields,source); }
  async extractWith<T>(url:string, extractor:PaperExtractor<T>): Promise<T> { return extractor.extract(await this.readPaper(url)); }
  getPaper(id: string): ResearchWork | undefined { return this.db.getWork(id); }
  recipe(work: ResearchWork): ResearchResponse<TrainingRecipe> { const source = makeEvidence(work.paperId, work, 'The paper metadata is verified; training configuration extraction requires an ingested full text or official configuration.', 'UNVERIFIED', 'C'); const recipe: TrainingRecipe = { method: 'unknown', teacher: {}, student: {}, objectives: missing<string[]>(), losses: missing<string[]>(), temperature: missing<number>(), alpha: missing<number>(), optimizer: {}, scheduler: {}, learning_rate: missing<number>(), batch_size: missing<number>(), gradient_accumulation: missing<number>(), sequence_length: missing<number>(), epochs: missing<number>(), training_steps: missing<number>(), warmup: missing<string>(), weight_decay: missing<number>(), precision: missing<string>(), gradient_clipping: missing<number>(), datasets: missing<string[]>(), missing_information: ['Full paper text or official configuration has not been ingested. No parameters were guessed.'], sources: [source] }; return { summary: `No training parameters are asserted for ${work.title}; unavailable fields are explicitly marked NOT_REPORTED. ${source.citationText}`, data: recipe, evidence: [source], references: [work], transparency: { expandedQueries: [], sourcesSearched: ['local database'], candidates: 1, retrievedAt: new Date().toISOString(), rankingRationale: ['provenance-first refusal to infer missing parameters'] } }; }
}
export interface GraphRelationshipMetadata { explicitRelation?: GraphRelation; }
export function classifyGraphRelationship(root:ResearchWork|undefined, target:ResearchWork, relation:GraphRelation, metadata:GraphRelationshipMetadata = {}):RelationshipClass { if(metadata.explicitRelation !== undefined && metadata.explicitRelation !== relation)return 'UNKNOWN'; if(metadata.explicitRelation === relation && relation !== 'related' && (!root || root.year === undefined || target.year === undefined || root.year === target.year))return 'DIRECT'; if(!root||root.year===undefined||target.year===undefined||relation==='related'||root.year===target.year)return 'UNKNOWN'; if(relation==='reference'&&target.year<root.year)return 'FOUNDATIONAL_CANDIDATE'; if(relation==='citation'&&target.year>root.year)return 'FOLLOW_UP_CANDIDATE'; return 'DIRECT'; }
function resolveGraphWork(db:ResearchStore, work:ResearchWork):ResearchWork { const existing=(work.doi&&db.getWork(work.doi))||(work.arxivId&&db.getWork(work.arxivId)); if(!existing||existing.paperId===work.paperId) return work; return {...existing,sourceProviders:[...new Set([...existing.sourceProviders,...work.sourceProviders])],versions:[...existing.versions,...work.versions],...(existing.semanticScholarId??work.semanticScholarId?{semanticScholarId:existing.semanticScholarId??work.semanticScholarId}:{}),...(existing.openAlexId??work.openAlexId?{openAlexId:existing.openAlexId??work.openAlexId}:{}),citationCount:Math.max(existing.citationCount??0,work.citationCount??0)}; }
function collectConflicts(selected:ResearchWork, alternate:ResearchWork, conflicts:SourceConflict[]):void { const fields:Array<keyof ResearchWork>=['doi','arxivId','year','venue','title']; for (const field of fields) { const first=selected[field]; const second=alternate[field]; if (first!==undefined&&second!==undefined&&String(first).trim().toLowerCase()!==String(second).trim().toLowerCase()) conflicts.push({field,selected:String(first),alternate:String(second),selectedSource:selected.sourceProviders.join(','),alternateSource:alternate.sourceProviders.join(',')}); } }
function matchesFilters(work: ResearchWork, filters: SearchFilters): boolean { const contains=(value:string|undefined,query:string|undefined)=>!query||Boolean(value?.toLowerCase().includes(query.toLowerCase())); return (filters.yearFrom===undefined||((work.year??-Infinity)>=filters.yearFrom))&&(filters.yearTo===undefined||((work.year??Infinity)<=filters.yearTo))&&(!filters.author||work.authors.some(author=>contains(author.name,filters.author)))&&contains(work.venue,filters.venue)&&(!filters.topic||Boolean(work.topics?.some(topic=>contains(topic,filters.topic)))); }
function comparisonKey(w: ResearchWork): string { if (w.doi) return `doi:${w.doi.trim().toLowerCase()}`; if (w.arxivId) return `arxiv:${w.arxivId.trim().toLowerCase()}`; return `metadata:${canonicalKey(w)}`; }
function canonicalKey(w: ResearchWork): string { return `${w.title.normalize('NFKD').replace(/[^\p{L}\p{N}]/gu, '').toLowerCase()}|${w.authors.slice(0, 3).map(a => normalizeAuthorName(a.name)).join('|')}`; }
function expand(q: string): string[] { const additions = /distillation/i.test(q) ? ['knowledge distillation','teacher student training','logit distillation','sequence-level distillation','on-policy distillation'] : [q]; return [...new Set([q, ...additions])]; }
function score(w: ResearchWork, q: string): number { const text = `${w.title} ${w.abstract ?? ''}`.toLowerCase(); return (text.includes(q.toLowerCase()) ? 10 : 0) + (w.citationCount ?? 0) / 1000 + (w.sourceProviders.includes('arxiv') ? 1 : 0); }