import type { ResearchWork, Evidence, ResearchResponse, TrainingRecipe, Reported, GraphItem, GraphRelation, AuthorProfile, GraphEdge, SourceConflict, RelationshipClass } from '../models/research.js';
import { ResearchDb } from '../database/db.js';
import { ArxivProvider } from '../providers/arxiv.js';
import { CrossrefProvider } from '../providers/crossref.js';
import { OpenAlexProvider } from '../providers/openalex.js';
import { SemanticScholarProvider } from '../providers/semantic-scholar.js';
import { makeEvidence, normalizeAuthorName } from './citations.js';
import { getReliabilityStats } from '../reliability/reliability.js';
import { PaperAcquirer } from '../ingestion/acquisition.js';
import { createHash } from 'node:crypto';
import { parseDocument, detectDocumentFormat, searchDocument } from '../ingestion/document.js';
import { PdfParserChain, GrobidClient, createConfiguredPdfFallbacks } from '../ingestion/pdf.js';
import { extractPaperFacts, type PaperFact } from '../extraction/heuristic.js';

const missing = <T>(): Reported<T> => ({ value: null, status: 'NOT_REPORTED' });
export interface SearchFilters { yearFrom?: number; yearTo?: number; author?: string; venue?: string; topic?: string; }
export class ResearchService {
  constructor(public readonly db = new ResearchDb(), private readonly arxiv = new ArxivProvider(), private readonly crossref = new CrossrefProvider(), private readonly openalex = new OpenAlexProvider(), private readonly semanticScholar = new SemanticScholarProvider(), private readonly acquirer = new PaperAcquirer(), private readonly pdfParser = new PdfParserChain(new GrobidClient(), createConfiguredPdfFallbacks())) {}
  async search(query: string, limit = 10, filters: SearchFilters = {}): Promise<ResearchResponse<ResearchWork[]>> { const expandedQueries = expand(query); const settled = await Promise.allSettled([this.arxiv.search(expandedQueries[0] ?? query, limit), this.crossref.search(query, limit), this.openalex.search(query, limit), this.semanticScholar.search(query, limit)]); const works = new Map<string, ResearchWork>(); const conflicts:SourceConflict[]=[]; for (const result of settled) if (result.status === 'fulfilled') for (const work of result.value) { const key = canonicalKey(work); const existing = works.get(key); if (existing) { collectConflicts(existing,work,conflicts); existing.sourceProviders = [...new Set([...existing.sourceProviders, ...work.sourceProviders])]; existing.versions.push(...work.versions); if (existing.doi === undefined && work.doi !== undefined) existing.doi = work.doi; if (existing.arxivId === undefined && work.arxivId !== undefined) existing.arxivId = work.arxivId; if (existing.semanticScholarId === undefined && work.semanticScholarId !== undefined) existing.semanticScholarId = work.semanticScholarId; if (existing.openAlexId === undefined && work.openAlexId !== undefined) existing.openAlexId = work.openAlexId; existing.citationCount = Math.max(existing.citationCount ?? 0, work.citationCount ?? 0); this.db.upsertWork(existing); } else { works.set(key, work); this.db.upsertWork(work); } } const ranked = [...works.values()].filter(work => matchesFilters(work, filters)).sort((a,b) => score(b, query)-score(a, query)).slice(0, limit); const evidence = ranked.map(w => makeEvidence(w.paperId, w, `Metadata identifies the work as “${w.title}”.`, 'DIRECT', 'C')); return { summary: ranked.length ? ranked.map(w => `${w.authors[0]?.name ?? 'Unknown'} et al. — ${w.title} ${w.year ? `(${w.year})` : ''} ${w.canonicalUrl ?? ''} ${evidence.find(e => e.sourceId === w.paperId)?.citationText ?? ''}`).join('\n') : 'No verified works were retrieved.', data: ranked, evidence, references: ranked, transparency: { query, expandedQueries, sourcesSearched: ['arxiv','crossref','openalex','semantic_scholar'], providerFailures: settled.map((result, index) => result.status === 'rejected' ? `${['arxiv','crossref','openalex','semantic_scholar'][index]}: ${String(result.reason)}` : undefined).filter((failure): failure is string => Boolean(failure)), reliability: getReliabilityStats(), candidates: works.size, retrievedAt: new Date().toISOString(), rankingRationale: ['lexical relevance', 'source availability', 'recency'], conflicts } }; }
  async graphAll(id:string, relation:GraphRelation, limit=20):Promise<ResearchResponse<GraphItem[]>> {
    const semanticCall = relation === 'reference' ? this.semanticScholar.getReferences(id, limit) : relation === 'citation' ? this.semanticScholar.getCitations(id, limit) : this.semanticScholar.getRelated(id, limit);
    const root = this.db.getWork(id);
    const openAlexId = root?.openAlexId ?? (id.startsWith('https://openalex.org/') ? id : undefined);
    const openAlexCall = openAlexId ? (relation === 'reference' ? this.openalex.getReferences(openAlexId, limit) : relation === 'citation' ? this.openalex.getCitations(openAlexId, limit) : Promise.resolve([])) : Promise.resolve([]);
    const settled = await Promise.allSettled([semanticCall, openAlexCall]);
    const candidates = settled.flatMap((result, index) => result.status === 'fulfilled' ? result.value.map(work => ({work, source: index === 0 ? 'semantic_scholar' : 'openalex'})) : []);
    const failures = settled.map((result, index) => result.status === 'rejected' ? `${index === 0 ? 'semantic_scholar' : 'openalex'}: ${String(result.reason)}` : undefined).filter((failure): failure is string => Boolean(failure));
    const conflicts:SourceConflict[] = [];
    const unique = new Map<string, {work:ResearchWork; source:string; providers:string[]}>();
    for (const candidate of candidates) {
      const work = resolveGraphWork(this.db, candidate.work);
      const key = work.doi ?? work.arxivId ?? canonicalKey(work);
      const existing = unique.get(key);
      if (existing) {
        collectConflicts(existing.work, work, conflicts);
        existing.work.sourceProviders = [...new Set([...existing.work.sourceProviders, ...work.sourceProviders])];
        existing.source = `${existing.source},${candidate.source}`;
        existing.providers = [...new Set([...existing.providers, candidate.source])];
      } else unique.set(key, {work, source:candidate.source, providers:[candidate.source]});
    }
    const items = [...unique.values()].slice(0, limit);
    const retrievedAt = new Date().toISOString();
    const evidence = items.map(item => makeEvidence(item.work.paperId, item.work, `${item.source} reports this work as a ${relation} of ${id}.`, 'DIRECT', item.providers.includes('semantic_scholar') ? 'B' : 'C'));
    const data = items.map((item, index) => ({work:item.work, relation, relationshipClass:classifyGraphRelationship(root, item.work, relation), source:item.source, evidence:evidence[index]!}));
    data.forEach((item, index) => {
      this.db.upsertWork(item.work);
      this.db.addEvidence(item.evidence, item.work.paperId);
      for (const provider of items[index]!.providers) this.db.upsertGraphEdge({sourcePaperId:id, targetPaperId:item.work.paperId, relation, provider, relationshipClass:item.relationshipClass, evidenceId:evidence[index]!.evidenceId, retrievedAt});
    });
    return {summary:data.length ? data.map(item => `${item.work.title} ${item.evidence.citationText}`).join('\n') : `No ${relation} works were reported.`, data, evidence, references:items.map(item => item.work), transparency:{expandedQueries:[], sourcesSearched:openAlexId ? ['semantic_scholar','openalex'] : ['semantic_scholar'], providerFailures:failures, candidates:candidates.length, retrievedAt, rankingRationale:['identifier-first cross-provider graph reconciliation'], conflicts}};
  }
  async graph(id:string, relation:GraphRelation, limit=20):Promise<ResearchResponse<GraphItem[]>> { const works=relation==='reference'?await this.semanticScholar.getReferences(id,limit):relation==='citation'?await this.semanticScholar.getCitations(id,limit):await this.semanticScholar.getRelated(id,limit); const root=this.db.getWork(id); const resolvedWorks=works.map(work=>resolveGraphWork(this.db,work)); const retrievedAt=new Date().toISOString(); const evidence=resolvedWorks.map(work=>makeEvidence(work.paperId,work,`Semantic Scholar reports this work as a ${relation} of ${id}.`,'DIRECT','B')); const data=resolvedWorks.map((work,index)=>({work,relation,relationshipClass:classifyGraphRelationship(root,work,relation),source:'semantic_scholar',evidence:evidence[index]!})); data.forEach((item,index)=>{ this.db.upsertWork(item.work); this.db.addEvidence(item.evidence,item.work.paperId); const edge:GraphEdge={sourcePaperId:id,targetPaperId:item.work.paperId,relation,provider:item.source,relationshipClass:item.relationshipClass,evidenceId:evidence[index]!.evidenceId,retrievedAt}; this.db.upsertGraphEdge(edge); }); return {summary:data.length?data.map(item=>`${item.work.title} ${item.evidence.citationText}`).join('\\n'):`No ${relation} works were reported.`,data,evidence,references:resolvedWorks,transparency:{expandedQueries:[],sourcesSearched:['semantic_scholar'],providerFailures:[],candidates:data.length,retrievedAt,rankingRationale:[`Semantic Scholar ${relation} graph response`]}}; }
  async resolveAuthor(id:string):Promise<AuthorProfile|undefined> { const profile=await this.semanticScholar.resolveAuthor(id); return profile?.authorId&&profile.name ? {authorId:profile.authorId,name:profile.name,aliases:profile.aliases ?? [],paperIds:(profile.papers ?? []).map(paper=>paper.paperId).filter((paperId):paperId is string=>Boolean(paperId)),source:'semantic_scholar'} : undefined; }
  async readPaper(url:string) { const acquired=await this.acquirer.acquire(url); const hash=createHash('sha256').update(acquired.body).digest('hex'); const cached=this.db.getParsedDocument(acquired.url,hash); if(cached)return cached; const parsed=detectDocumentFormat(acquired.contentType,acquired.body)==='pdf' ? await this.pdfParser.process(acquired.body,acquired.url) : parseDocument(acquired); this.db.saveParsedDocument(parsed,hash); return parsed; }
  async searchWithinPaper(url:string, query:string, limit=10) { return searchDocument(await this.readPaper(url), query, limit); }
  async extractPaperFacts(url:string): Promise<PaperFact[]> { return extractPaperFacts(await this.readPaper(url)); }
  getPaper(id: string): ResearchWork | undefined { return this.db.getWork(id); }
  recipe(work: ResearchWork): ResearchResponse<TrainingRecipe> { const source = makeEvidence(work.paperId, work, 'The paper metadata is verified; training configuration extraction requires an ingested full text or official configuration.', 'UNVERIFIED', 'C'); const recipe: TrainingRecipe = { method: 'unknown', teacher: {}, student: {}, objectives: missing<string[]>(), losses: missing<string[]>(), temperature: missing<number>(), alpha: missing<number>(), optimizer: {}, scheduler: {}, learning_rate: missing<number>(), batch_size: missing<number>(), gradient_accumulation: missing<number>(), sequence_length: missing<number>(), epochs: missing<number>(), training_steps: missing<number>(), warmup: missing<string>(), weight_decay: missing<number>(), precision: missing<string>(), gradient_clipping: missing<number>(), datasets: missing<string[]>(), missing_information: ['Full paper text or official configuration has not been ingested. No parameters were guessed.'], sources: [source] }; return { summary: `No training parameters are asserted for ${work.title}; unavailable fields are explicitly marked NOT_REPORTED. ${source.citationText}`, data: recipe, evidence: [source], references: [work], transparency: { expandedQueries: [], sourcesSearched: ['local database'], candidates: 1, retrievedAt: new Date().toISOString(), rankingRationale: ['provenance-first refusal to infer missing parameters'] } }; }
}
export function classifyGraphRelationship(root:ResearchWork|undefined, target:ResearchWork, relation:GraphRelation):RelationshipClass { if(!root||root.year===undefined||target.year===undefined||relation==='related'||root.year===target.year)return 'UNKNOWN'; if(relation==='reference'&&target.year<root.year)return 'FOUNDATIONAL_CANDIDATE'; if(relation==='citation'&&target.year>root.year)return 'FOLLOW_UP_CANDIDATE'; return 'DIRECT'; }
function resolveGraphWork(db:ResearchDb, work:ResearchWork):ResearchWork { const existing=(work.doi&&db.getWork(work.doi))||(work.arxivId&&db.getWork(work.arxivId)); if(!existing||existing.paperId===work.paperId) return work; return {...existing,sourceProviders:[...new Set([...existing.sourceProviders,...work.sourceProviders])],versions:[...existing.versions,...work.versions],...(existing.semanticScholarId??work.semanticScholarId?{semanticScholarId:existing.semanticScholarId??work.semanticScholarId}:{}),...(existing.openAlexId??work.openAlexId?{openAlexId:existing.openAlexId??work.openAlexId}:{}),citationCount:Math.max(existing.citationCount??0,work.citationCount??0)}; }
function collectConflicts(selected:ResearchWork, alternate:ResearchWork, conflicts:SourceConflict[]):void { const fields:Array<keyof ResearchWork>=['doi','arxivId','year','venue','title']; for (const field of fields) { const first=selected[field]; const second=alternate[field]; if (first!==undefined&&second!==undefined&&String(first).trim().toLowerCase()!==String(second).trim().toLowerCase()) conflicts.push({field,selected:String(first),alternate:String(second),selectedSource:selected.sourceProviders.join(','),alternateSource:alternate.sourceProviders.join(',')}); } }
function matchesFilters(work: ResearchWork, filters: SearchFilters): boolean { const contains=(value:string|undefined,query:string|undefined)=>!query||Boolean(value?.toLowerCase().includes(query.toLowerCase())); return (filters.yearFrom===undefined||((work.year??-Infinity)>=filters.yearFrom))&&(filters.yearTo===undefined||((work.year??Infinity)<=filters.yearTo))&&(!filters.author||work.authors.some(author=>contains(author.name,filters.author)))&&contains(work.venue,filters.venue)&&(!filters.topic||Boolean(work.topics?.some(topic=>contains(topic,filters.topic)))); }
function canonicalKey(w: ResearchWork): string { return `${w.title.normalize('NFKD').replace(/[^\p{L}\p{N}]/gu, '').toLowerCase()}|${w.authors.slice(0, 3).map(a => normalizeAuthorName(a.name)).join('|')}`; }
function expand(q: string): string[] { const additions = /distillation/i.test(q) ? ['knowledge distillation','teacher student training','logit distillation','sequence-level distillation','on-policy distillation'] : [q]; return [...new Set([q, ...additions])]; }
function score(w: ResearchWork, q: string): number { const text = `${w.title} ${w.abstract ?? ''}`.toLowerCase(); return (text.includes(q.toLowerCase()) ? 10 : 0) + (w.citationCount ?? 0) / 1000 + (w.sourceProviders.includes('arxiv') ? 1 : 0); }