import { author, bibtex, normalizeArxivId, paperId } from '../research/citations.js';
import type { ResearchWork } from '../models/research.js';
import { createConfiguredProviderFetcher } from '../reliability/provider-fetcher.js';

export class ArxivProvider {
  constructor(fetcher: typeof fetch = fetch) { this.fetcher = createConfiguredProviderFetcher(fetcher, { minIntervalMs: 250 }); }
  private readonly fetcher: typeof fetch;
  async searchById(arxivId:string):Promise<ResearchWork[]> { const normalized=normalizeArxivId(arxivId); const url = `https://export.arxiv.org/api/query?search_query=id:${encodeURIComponent(normalized)}&start=0&max_results=1`; const response=await this.fetcher(url,{headers:{accept:'application/atom+xml'}}); if(!response.ok)throw new Error(`arXiv request failed: ${response.status}`); const xml=await response.text(); if(!/<feed\b[\s>]/i.test(xml)||!/<\/feed>/i.test(xml))throw new Error('invalid arXiv response: expected Atom feed'); return [...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].map(m=>this.parse(m[1] ?? '')).filter(Boolean) as ResearchWork[]; }
  async search(query: string, limit = 10): Promise<ResearchWork[]> { const url = `https://export.arxiv.org/api/query?search_query=all:${encodeURIComponent(query)}&start=0&max_results=${Math.min(limit, 50)}`; const response = await this.fetcher(url, { headers: { accept: 'application/atom+xml' } }); if (!response.ok) throw new Error(`arXiv request failed: ${response.status}`); const xml = await response.text(); if(!/<feed\b[\s>]/i.test(xml)||!/<\/feed>/i.test(xml))throw new Error('invalid arXiv response: expected Atom feed'); return [...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].map(m => this.parse(m[1] ?? '')).filter(Boolean) as ResearchWork[]; }
  private parse(entry: string): ResearchWork | undefined { const text = (tag: string) => entry.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`))?.[1]?.trim().replace(/<!\[CDATA\[|\]\]>/g, ''); const id = text('id'); if (!id) return; const arxivId = normalizeArxivId(id); const title = text('title')?.replace(/\s+/g, ' '); if (!title) return; const authors = [...entry.matchAll(/<author>[\s\S]*?<name>([\s\S]*?)<\/name>[\s\S]*?<\/author>/g)].map(m => author((m[1] ?? '').trim())); const published = text('published'); const year = published ? Number(published.slice(0, 4)) : undefined; const work: ResearchWork = { paperId: paperId(title, authors, undefined, arxivId), title, authors, ...(year ? { year } : {}), arxivId, canonicalUrl: `https://arxiv.org/abs/${arxivId}`, pdfUrl: `https://arxiv.org/pdf/${arxivId}`, publicationStatus: 'preprint', bibtex: '', sourceProviders: ['arxiv'], versions: [{ versionId: `${arxivId}:latest`, sourceId: 'arxiv', canonicalUrl: `https://arxiv.org/abs/${arxivId}`, pdfUrl: `https://arxiv.org/pdf/${arxivId}`, ...(published ? { submittedAt: published } : {}) }], ...(text('summary') ? { abstract: text('summary')!.replace(/\s+/g, ' ') } : {}) }; work.bibtex = bibtex(work); return work; }
}
