import { author, bibtex, normalizeDoi, paperId } from '../research/citations.js';
import type { ResearchWork } from '../models/research.js';
import { createConfiguredProviderFetcher } from '../reliability/provider-fetcher.js';
export class CrossrefProvider {
  constructor(fetcher: typeof fetch = fetch) { this.fetcher = createConfiguredProviderFetcher(fetcher, { minIntervalMs: 250 }); }
  private readonly fetcher: typeof fetch;
  private mapItem(item: unknown): ResearchWork { const x = item as any; if(!x||typeof x!=='object'||!Array.isArray(x.title)||typeof x.title[0]!=='string'||!x.title[0].trim()) throw new Error('invalid Crossref response: item title is missing'); const authors = (x.author ?? []).map((a: any) => author([a.given, a.family].filter(Boolean).join(' '))); const title = x.title[0] as string; const year = x.published?.['date-parts']?.[0]?.[0]; const doi = typeof x.DOI === 'string' ? normalizeDoi(x.DOI) : undefined; const work: ResearchWork = { paperId: paperId(title, authors, doi), title, authors, ...(year ? {year} : {}), ...(doi ? {doi} : {}), ...(typeof x['container-title']?.[0] === 'string' ? {venue: x['container-title'][0] as string} : {}), ...(typeof x.URL === 'string' ? {canonicalUrl: x.URL} : {}), publicationStatus: x.type === 'journal-article' ? 'journal' : 'unknown', bibtex: '', sourceProviders: ['crossref'], versions: [{versionId: `${doi ?? title}:crossref`, sourceId: 'crossref', ...(typeof x.URL === 'string' ? {canonicalUrl: x.URL} : {})}] }; work.bibtex = bibtex(work); return work; }
  async search(query: string, limit = 10): Promise<ResearchWork[]> { const r = await this.fetcher(`https://api.crossref.org/works?query.bibliographic=${encodeURIComponent(query)}&rows=${Math.min(limit, 50)}`, { headers: { accept: 'application/json' } }); if (!r.ok) throw new Error(`Crossref request failed: ${r.status}`); const data = await r.json() as {message?: {items?: unknown}}; if(!data.message||!Array.isArray(data.message.items)) throw new Error('invalid Crossref response: expected message.items array'); return data.message.items.map(x => this.mapItem(x)); }
  async getByDoi(doi: string): Promise<ResearchWork | undefined> { const normalized = normalizeDoi(doi); const r = await this.fetcher(`https://api.crossref.org/works/${encodeURIComponent(normalized)}`, { headers: { accept: 'application/json' } }); if (r.status === 404) return undefined; if (!r.ok) throw new Error(`Crossref request failed: ${r.status}`); const data = await r.json() as {message?: unknown}; if (!data.message || typeof data.message !== 'object') throw new Error('invalid Crossref response: expected message object'); return this.mapItem(data.message); }
}
