export type ImplementationStatus = 'OFFICIAL' | 'AUTHOR_MAINTAINED' | 'ORGANIZATION_OFFICIAL' | 'COMMUNITY_REPRODUCTION' | 'UNKNOWN';
import { createReliableFetcher } from '../reliability/reliability.js';
export interface GitHubRepository { id: number; fullName: string; name: string; owner: string; description?: string; htmlUrl: string; defaultBranch?: string; updatedAt?: string; stars?: number; topics: string[]; implementationStatus: ImplementationStatus; examinedCommitSha?: string; source: 'github'; }
export interface GitHubContent { path: string; sha: string; size?: number; htmlUrl?: string; downloadUrl?: string; content?: string; encoding?: string; repository: string; commitSha?: string; source: 'github'; }
export interface GitHubDirectoryEntry { path: string; name: string; type: 'file' | 'dir' | string; sha: string; htmlUrl?: string; repository: string; source: 'github'; }
interface GitHubPayload { id?: number; full_name?: string; name?: string; owner?: {login?: string}; description?: string|null; html_url?: string; default_branch?: string; updated_at?: string; stargazers_count?: number; topics?: string[]; }
export function mapGitHubRepository(x: GitHubPayload): GitHubRepository | undefined { if (!x.id || !x.full_name || !x.name || !x.owner?.login || !x.html_url) return undefined; return {id:x.id,fullName:x.full_name,name:x.name,owner:x.owner.login,...(x.description ? {description:x.description}:{}),htmlUrl:x.html_url,...(x.default_branch ? {defaultBranch:x.default_branch}:{}),...(x.updated_at ? {updatedAt:x.updated_at}:{}),...(x.stargazers_count !== undefined ? {stars:x.stargazers_count}:{}),topics:x.topics ?? [],implementationStatus:'UNKNOWN',source:'github'}; }
export function decodeGitHubContent(content: GitHubContent): string | undefined { if (!content.content) return undefined; if (content.encoding === 'base64') return Buffer.from(content.content.replaceAll('\n',''), 'base64').toString('utf8'); return content.content; }
export class GitHubProvider {
  constructor(fetcher: typeof fetch = fetch, private readonly token = process.env.GITHUB_TOKEN) { this.fetcher=createReliableFetcher(fetcher,{minIntervalMs:100}); } private readonly fetcher: typeof fetch;
  async searchRepositories(query:string,limit=10):Promise<GitHubRepository[]> { const u=new URL('https://api.github.com/search/repositories'); u.searchParams.set('q',query); u.searchParams.set('per_page',String(Math.min(limit,100))); const data=await this.request(u); return (data?.items ?? []).map(mapGitHubRepository).filter(Boolean) as GitHubRepository[]; }
  async resolveRevision(owner:string,repo:string,ref:string):Promise<string|undefined> { const u=new URL(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/commits/${encodeURIComponent(ref)}`); const x=await this.request(u); return typeof x?.sha === 'string' ? x.sha : undefined; }
  async listContents(owner:string,repo:string,path='',ref?:string):Promise<GitHubDirectoryEntry[]> { const suffix=path ? `/${path.split('/').map(encodeURIComponent).join('/')}` : ''; const u=new URL(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents${suffix}`); if(ref) u.searchParams.set('ref',ref); const data=await this.request(u); if(!Array.isArray(data)) return []; return data.filter((x:any)=>typeof x?.path==='string'&&typeof x?.name==='string'&&typeof x?.sha==='string').map((x:any)=>({path:x.path,name:x.name,type:x.type,sha:x.sha,...(x.html_url?{htmlUrl:x.html_url}:{}),repository:`${owner}/${repo}`,source:'github'})); }
  async getContent(owner:string,repo:string,path:string,ref?:string):Promise<GitHubContent|undefined> { const u=new URL(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${path.split('/').map(encodeURIComponent).join('/')}`); if(ref) u.searchParams.set('ref',ref); const x=await this.request(u); if(!x?.path||!x.sha) return undefined; return {path:x.path,sha:x.sha,...(x.size!==undefined?{size:x.size}:{}),...(x.html_url?{htmlUrl:x.html_url}:{}),...(x.download_url?{downloadUrl:x.download_url}:{}),...(x.content?{content:x.content}:{}),...(x.encoding?{encoding:x.encoding}:{}),repository:`${owner}/${repo}`,source:'github'}; }
  private async request(u:URL):Promise<any> { const headers:Record<string,string>={accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'OpenPapers/0.1'}; if(this.token) headers.authorization=`Bearer ${this.token}`; const r=await this.fetcher(u.toString(),{headers}); if(!r.ok) throw new Error(`GitHub request failed: ${r.status}`); return r.json(); }
}
