import { author, bibtex, paperId } from '../research/citations.js';
import type { ResearchWork } from '../models/research.js';
import { createReliableFetcher } from '../reliability/reliability.js';

export interface OpenAlexWork { id?: string; doi?: string; title?: string; publication_year?: number; cited_by_count?: number; referenced_works?: string[]; authorships?: Array<{author?: {id?: string; display_name?: string; orcid?: string}}>; topics?: Array<{display_name?: string}>; primary_location?: {source?: {display_name?: string}}; open_access?: {is_oa?: boolean}; best_oa_location?: {landing_page_url?: string; pdf_url?: string}; }
export function mapOpenAlexWork(x: OpenAlexWork): ResearchWork | undefined {
  if (!x.title) return undefined;
  const authors = (x.authorships ?? []).map(a => a.author?.display_name ? author(a.author.display_name, a.author.orcid) : undefined).filter(Boolean) as ReturnType<typeof author>[];
  const authorIds = [...new Set((x.authorships ?? []).map(a => a.author?.id).filter((id): id is string => Boolean(id)))];
  const topics = [...new Set((x.topics ?? []).map(topic => topic.display_name?.trim()).filter((topic): topic is string => Boolean(topic)))];
  const doi = x.doi?.replace(/^https?:\/\/doi.org\//i, '').toLowerCase();
  const work: ResearchWork = { paperId: paperId(x.title, authors, doi), title: x.title, authors, ...(authorIds.length ? {authorIds} : {}), ...(topics.length ? {topics} : {}), ...(x.id ? {openAlexId:x.id} : {}), ...(x.publication_year ? {year:x.publication_year} : {}), ...(doi ? {doi} : {}), ...(x.primary_location?.source?.display_name ? {venue:x.primary_location.source.display_name} : {}), ...(x.best_oa_location?.landing_page_url ? {canonicalUrl:x.best_oa_location.landing_page_url} : {canonicalUrl:x.id ?? 'https://openalex.org/'}), ...(x.best_oa_location?.pdf_url ? {pdfUrl:x.best_oa_location.pdf_url} : {}), ...(x.cited_by_count !== undefined ? {citationCount:x.cited_by_count} : {}), publicationStatus:'unknown', bibtex:'', sourceProviders:['openalex'], versions:[{versionId:`${x.id ?? x.title}:openalex`,sourceId:'openalex', ...(x.best_oa_location?.landing_page_url ? {canonicalUrl:x.best_oa_location.landing_page_url} : {}), ...(x.best_oa_location?.pdf_url ? {pdfUrl:x.best_oa_location.pdf_url} : {})}] };
  work.bibtex = bibtex(work);
  return work;
}
export class OpenAlexProvider { constructor(fetcher: typeof fetch = fetch) { this.fetcher=createReliableFetcher(fetcher,{minIntervalMs:250}); } private readonly fetcher: typeof fetch; async search(query:string,limit=10):Promise<ResearchWork[]> { const url = new URL('https://api.openalex.org/works'); url.searchParams.set('search', query); url.searchParams.set('per-page', String(Math.min(limit,100))); url.searchParams.set('select','id,doi,title,publication_year,cited_by_count,authorships,topics,primary_location,open_access,best_oa_location'); if (process.env.OPENALEX_EMAIL) url.searchParams.set('mailto', process.env.OPENALEX_EMAIL); const response=await this.fetcher(url,{headers:{accept:'application/json'}}); if(!response.ok) throw new Error(`OpenAlex request failed: ${response.status}`); const data=await response.json() as {results?:OpenAlexWork[]}; return (data.results ?? []).map(mapOpenAlexWork).filter(Boolean) as ResearchWork[]; }
  async getReferences(id:string,limit=20):Promise<ResearchWork[]> { const url=new URL(`https://api.openalex.org/works/${encodeURIComponent(id)}`); url.searchParams.set('select','referenced_works'); const response=await this.fetcher(url,{headers:{accept:'application/json'}}); if(!response.ok) throw new Error(`OpenAlex request failed: ${response.status}`); const parent=await response.json() as OpenAlexWork; const ids=(parent.referenced_works??[]).slice(0,Math.min(limit,100)); const works=await Promise.all(ids.map(workId=>this.getWork(workId))); return works.filter((work):work is ResearchWork=>Boolean(work)); }
  async getCitations(id:string,limit=20):Promise<ResearchWork[]> { const url=new URL('https://api.openalex.org/works'); url.searchParams.set('filter',`cites:${id}`); url.searchParams.set('per-page',String(Math.min(limit,100))); url.searchParams.set('select','id,doi,title,publication_year,cited_by_count,authorships,topics,primary_location,open_access,best_oa_location'); const response=await this.fetcher(url,{headers:{accept:'application/json'}}); if(!response.ok) throw new Error(`OpenAlex request failed: ${response.status}`); const data=await response.json() as {results?:OpenAlexWork[]}; return (data.results??[]).map(mapOpenAlexWork).filter(Boolean) as ResearchWork[]; }
  private async getWork(id:string):Promise<ResearchWork|undefined> { const url=new URL(`https://api.openalex.org/works/${encodeURIComponent(id)}`); url.searchParams.set('select','id,doi,title,publication_year,cited_by_count,authorships,topics,primary_location,open_access,best_oa_location'); const response=await this.fetcher(url,{headers:{accept:'application/json'}}); if(!response.ok) return undefined; return mapOpenAlexWork(await response.json() as OpenAlexWork); }
}
