import { author, bibtex, normalizeArxivId, normalizeDoi, paperId } from '../research/citations.js';
import type { ResearchWork } from '../models/research.js';
import { createConfiguredProviderFetcher } from '../reliability/provider-fetcher.js';

export interface SemanticScholarPaper { paperId?: string; title?: string; authors?: Array<{authorId?: string|null; name?: string}>; year?: number; venue?: string; citationCount?: number; externalIds?: {ArXiv?: string; DOI?: string; [key:string]: string|undefined}; url?: string; openAccessPdf?: {url?: string|null}; }
export interface SemanticScholarAuthor { authorId?: string; name?: string; aliases?: string[]; papers?: Array<{paperId?: string|null}>; }
const FIELDS = 'paperId,title,authors,year,venue,externalIds,url,openAccessPdf,citationCount';

export function mapSemanticScholarPaper(x: SemanticScholarPaper): ResearchWork | undefined { if (!x.title || !x.paperId) return undefined; const authors = (x.authors ?? []).filter(a => a.name).map(a => author(a.name!)); const authorIds = (x.authors ?? []).map(a => a.authorId ?? undefined).filter((id): id is string => Boolean(id)); const arxiv = x.externalIds?.ArXiv ? normalizeArxivId(x.externalIds.ArXiv) : undefined; const doi = x.externalIds?.DOI ? normalizeDoi(x.externalIds.DOI) : undefined; const work: ResearchWork = { paperId: paperId(x.title, authors, doi, arxiv), title:x.title, authors, ...(authorIds.length ? {authorIds} : {}), ...(x.year ? {year:x.year} : {}), ...(x.venue ? {venue:x.venue} : {}), ...(doi ? {doi} : {}), ...(arxiv ? {arxivId:arxiv} : {}), semanticScholarId:x.paperId, ...(x.url ? {canonicalUrl:x.url} : {}), ...(x.openAccessPdf?.url ? {pdfUrl:x.openAccessPdf.url} : {}), ...(x.citationCount !== undefined ? {citationCount:x.citationCount} : {}), publicationStatus:'unknown', bibtex:'', sourceProviders:['semantic_scholar'], versions:[{versionId:`${x.paperId}:semantic_scholar`,sourceId:'semantic_scholar', ...(x.url ? {canonicalUrl:x.url} : {}), ...(x.openAccessPdf?.url ? {pdfUrl:x.openAccessPdf.url} : {})}] }; work.bibtex=bibtex(work); return work; }
export class SemanticScholarProvider {
  constructor(fetcher: typeof fetch = fetch, private readonly apiKey = process.env.SEMANTIC_SCHOLAR_API_KEY) { this.fetcher=createConfiguredProviderFetcher(fetcher,{minIntervalMs:1000}); }
  private readonly fetcher: typeof fetch;
  async search(query:string, limit=10):Promise<ResearchWork[]> { const url = new URL('https://api.semanticscholar.org/graph/v1/paper/search'); url.searchParams.set('query',query); url.searchParams.set('limit',String(Math.min(limit,100))); url.searchParams.set('fields',FIELDS); const data=await this.request(url); if(!data||!Array.isArray(data.data))throw new Error('invalid Semantic Scholar response: expected data array'); return data.data.map(mapSemanticScholarPaper).filter(Boolean) as ResearchWork[]; }
  async getPaper(id:string):Promise<ResearchWork|undefined> { const url = new URL(`https://api.semanticscholar.org/graph/v1/paper/${encodeURIComponent(id)}`); url.searchParams.set('fields',FIELDS); const data=await this.request(url); return data ? mapSemanticScholarPaper(data as SemanticScholarPaper) : undefined; }
  async getReferences(id:string, limit=20):Promise<ResearchWork[]> { return this.getNeighbors(id,'references',limit); }
  async getCitations(id:string, limit=20):Promise<ResearchWork[]> { return this.getNeighbors(id,'citations',limit); }
  async getRelated(id:string, limit=20):Promise<ResearchWork[]> { const url=new URL(`https://api.semanticscholar.org/recommendations/v1/papers/forpaper/${encodeURIComponent(id)}`); url.searchParams.set('limit',String(Math.min(limit,100))); url.searchParams.set('fields',FIELDS); const data=await this.request(url); if(!data||!Array.isArray(data.recommendedPapers))throw new Error('invalid Semantic Scholar response: expected recommendedPapers array'); return data.recommendedPapers.map(mapSemanticScholarPaper).filter(Boolean) as ResearchWork[]; }
  async resolveAuthor(id:string):Promise<SemanticScholarAuthor|undefined> { const url=new URL(`https://api.semanticscholar.org/graph/v1/author/${encodeURIComponent(id)}`); url.searchParams.set('fields','authorId,name,aliases,papers.paperId'); const data=await this.request(url); if(!data||typeof data!=='object')throw new Error('invalid Semantic Scholar response: expected author object'); return data as SemanticScholarAuthor; }
  private async getNeighbors(id:string, relation:'references'|'citations', limit:number):Promise<ResearchWork[]> { const paperField=relation==='references'?'citedPaper':'citingPaper'; const url=new URL(`https://api.semanticscholar.org/graph/v1/paper/${encodeURIComponent(id)}/${relation}`); url.searchParams.set('fields',FIELDS.split(',').map(field=>`${paperField}.${field}`).join(',')); url.searchParams.set('limit',String(Math.min(limit,100))); const data=await this.request(url); if(!data||!Array.isArray(data.data))throw new Error('invalid Semantic Scholar response: expected data array'); return data.data.map((entry:{citedPaper?:SemanticScholarPaper; citingPaper?:SemanticScholarPaper})=>entry[paperField]).filter((paper:SemanticScholarPaper|undefined): paper is SemanticScholarPaper=>Boolean(paper)).map(mapSemanticScholarPaper).filter(Boolean) as ResearchWork[]; }
  private async request(url:URL):Promise<any|undefined> { const headers:Record<string,string>={accept:'application/json','User-Agent':'OpenPapers/0.1'}; if(this.apiKey) headers['x-api-key']=this.apiKey; const response=await this.fetcher(url.toString(),{headers}); if(response.status===429) throw new Error('HTTP 429: Semantic Scholar rate limit reached'); if(!response.ok) throw new Error(`Semantic Scholar request failed: ${response.status}`); return response.json(); }
}
