import { z } from 'zod/v4';
import { McpServer } from '@modelcontextprotocol/server';
import type { ResearchService } from '../research/service.js';

const result = (data: unknown, summary: string) => ({ content: [{ type: 'text' as const, text: summary }], structuredContent: data as Record<string, unknown> });
export function registerTools(server: McpServer, research: ResearchService): void {
  server.registerTool('search_papers', { title: 'Search papers', description: 'Search verified scholarly metadata across arXiv and Crossref. Results include provenance and transparent ranking.', inputSchema: z.object({ query: z.string().min(1), limit: z.number().int().min(1).max(50).default(10), year_from: z.number().int().optional(), year_to: z.number().int().optional() }) }, async ({query, limit}) => { const r = await research.search(query, limit); return result(r, r.summary); });
  server.registerTool('get_paper', { title: 'Get paper', description: 'Retrieve a canonical research work by paper ID, DOI, or arXiv ID.', inputSchema: z.object({ paper_id: z.string().min(1) }) }, async ({paper_id}) => { const p = research.getPaper(paper_id); if (!p) return { content: [{type:'text' as const, text: 'NOT_FOUND: no verified paper exists for this identifier.'}], isError: true }; return result({data: p, evidence: [], references: [p]}, `${p.authors.map(a=>a.name).join(', ')} — ${p.title}`); });
  server.registerTool('extract_training_recipe', { title: 'Extract training recipe', description: 'Return only source-backed training parameters. Missing values are never guessed.', inputSchema: z.object({ paper_id: z.string().min(1) }) }, async ({paper_id}) => { const p = research.getPaper(paper_id); if (!p) return {content:[{type:'text' as const,text:'NOT_FOUND: paper is not in the local verified database.'}],isError:true}; const r = research.recipe(p); return result(r, r.summary); });
  server.registerTool('get_bibtex', { title: 'Get BibTeX', description: 'Return canonical BibTeX without fabricating absent metadata.', inputSchema: z.object({paper_id:z.string().min(1)}) }, async ({paper_id}) => { const p=research.getPaper(paper_id); if(!p) return {content:[{type:'text' as const,text:'NOT_FOUND'}],isError:true}; return result({bibtex:p.bibtex, paper:p}, p.bibtex); });
  server.registerTool('research_topic', { title: 'Research topic', description: 'Build a provenance-preserving literature overview. Synthesis is labeled; no unsupported claims are emitted.', inputSchema: z.object({topic:z.string().min(1), objective:z.enum(['implement','literature_review']).default('literature_review'), depth:z.enum(['quick','deep']).default('quick'), limit:z.number().int().min(1).max(50).default(15)}) }, async ({topic, limit}) => { const r=await research.search(topic,limit); return result({...r, synthesis: r.data.length ? `Retrieved ${r.data.length} works for the topic. This is a retrieval result, not an assertion that the works use identical methods.` : 'No verified literature was retrieved.'}, r.summary); });
}
