import { z } from 'zod/v4';
import { McpServer } from '@modelcontextprotocol/server';
import type { ResearchService } from '../research/service.js';

import { validateCitationIntegrity } from '../research/verification.js';
import type { ResearchResponse } from '../models/research.js';
import { makeEvidence } from '../research/citations.js';
import { registerEcosystemTools } from './tool-modules/ecosystem.js';

const result = (data: unknown, summary: string) => { const candidate = data as Partial<ResearchResponse<unknown>>; if (Array.isArray(candidate.evidence) && Array.isArray(candidate.references)) { const integrity = validateCitationIntegrity(candidate as ResearchResponse<unknown>); if (!integrity.valid) return { content: [{ type: 'text' as const, text: `Citation integrity failure: ${integrity.errors.join('; ')}` }], structuredContent: { integrity } as Record<string, unknown>, isError: true }; } return { content: [{ type: 'text' as const, text: summary }], structuredContent: data as Record<string, unknown> }; };
export function registerTools(server: McpServer, research: ResearchService): void {
  server.registerTool('search_papers', { title: 'Search papers', description: 'Search verified scholarly metadata across arXiv and Crossref. Results include provenance and transparent ranking.', inputSchema: z.object({ query: z.string().min(1), limit: z.number().int().min(1).max(50).default(10), year_from: z.number().int().optional(), year_to: z.number().int().optional(), author: z.string().optional(), venue: z.string().optional(), topic: z.string().optional() }) }, async ({query, limit, year_from, year_to, author, venue, topic}) => { const r = await research.search(query, limit, { ...(year_from===undefined?{}:{yearFrom:year_from}), ...(year_to===undefined?{}:{yearTo:year_to}), ...(author===undefined?{}:{author}), ...(venue===undefined?{}:{venue}), ...(topic===undefined?{}:{topic}) }); return result(r, r.summary); });
  server.registerTool('get_references', { title:'Get references', description:'Retrieve Semantic Scholar references with provenance.', inputSchema:z.object({paper_id:z.string().min(1),limit:z.number().int().min(1).max(100).default(20)}) }, async ({paper_id,limit}) => { const r=await research.graphAll(paper_id,'reference',limit); return result(r,r.summary); });
  server.registerTool('get_citations', { title:'Get citations', description:'Retrieve Semantic Scholar citing works with provenance.', inputSchema:z.object({paper_id:z.string().min(1),limit:z.number().int().min(1).max(100).default(20)}) }, async ({paper_id,limit}) => { const r=await research.graphAll(paper_id,'citation',limit); return result(r,r.summary); });
  server.registerTool('get_related_papers', { title:'Get related papers', description:'Retrieve Semantic Scholar recommendations with provenance.', inputSchema:z.object({paper_id:z.string().min(1),limit:z.number().int().min(1).max(100).default(20)}) }, async ({paper_id,limit}) => { const r=await research.graphAll(paper_id,'related',limit); return result(r,r.summary); });
  server.registerTool('resolve_author', { title:'Resolve author', description:'Resolve a Semantic Scholar author profile and linked paper identifiers.', inputSchema:z.object({author_id:z.string().min(1)}) }, async ({author_id}) => { const profile=await research.resolveAuthor(author_id); if(!profile)return {content:[{type:'text' as const,text:'NOT_FOUND: no Semantic Scholar author profile was resolved.'}],isError:true}; return {content:[{type:'text' as const,text:`${profile.name} (${profile.authorId})`}],structuredContent:{author:profile}}; });
  server.registerTool('get_paper', { title: 'Get paper', description: 'Retrieve a canonical research work by paper ID, DOI, or arXiv ID.', inputSchema: z.object({ paper_id: z.string().min(1) }) }, async ({paper_id}) => { const p = research.getPaper(paper_id); if (!p) return { content: [{type:'text' as const, text: 'NOT_FOUND: no verified paper exists for this identifier.'}], isError: true }; const e=makeEvidence(p.paperId,p,`Metadata identifies the work as “${p.title}”.`); return result({data: p, evidence: [e], references: [p]}, `${p.authors.map(a=>a.name).join(', ')} — ${p.title} ${e.citationText}`); });
  server.registerTool('extract_training_recipe', { title: 'Extract training recipe', description: 'Return only source-backed training parameters. Missing values are never guessed.', inputSchema: z.object({ paper_id: z.string().min(1) }) }, async ({paper_id}) => { const p = research.getPaper(paper_id); if (!p) return {content:[{type:'text' as const,text:'NOT_FOUND: paper is not in the local verified database.'}],isError:true}; const r = research.recipe(p); return result(r, r.summary); });
  server.registerTool('get_bibtex', { title: 'Get BibTeX', description: 'Return canonical BibTeX without fabricating absent metadata.', inputSchema: z.object({paper_id:z.string().min(1)}) }, async ({paper_id}) => { const p=research.getPaper(paper_id); if(!p) return {content:[{type:'text' as const,text:'NOT_FOUND'}],isError:true}; const e=makeEvidence(p.paperId,p,`Metadata identifies the work as “${p.title}”.`); return result({bibtex:p.bibtex, paper:p, evidence:[e], references:[p]}, `${p.bibtex}\n${e.citationText}`); });
  server.registerTool('research_topic', { title: 'Research topic', description: 'Build a provenance-preserving literature overview. Synthesis is labeled; no unsupported claims are emitted.', inputSchema: z.object({topic:z.string().min(1), objective:z.enum(['implement','literature_review']).default('literature_review'), depth:z.enum(['quick','deep']).default('quick'), limit:z.number().int().min(1).max(50).default(15)}) }, async ({topic, limit}) => { const r=await research.search(topic,limit); return result({...r, synthesis: r.data.length ? `Retrieved ${r.data.length} works for the topic. This is a retrieval result, not an assertion that the works use identical methods.` : 'No verified literature was retrieved.'}, r.summary); });
  registerEcosystemTools(server, { research });
 }
