import { z } from 'zod/v4';
import { McpServer } from '@modelcontextprotocol/server';
import type { ResearchService } from '../research/service.js';

import { validateCitationIntegrity } from '../research/verification.js';
import type { ResearchResponse, Locator } from '../models/research.js';
import { makeEvidence } from '../research/citations.js';
import { registerEcosystemTools } from './tool-modules/ecosystem.js';

const result = (data: unknown, summary: string) => { const candidate = data as Partial<ResearchResponse<unknown>>; if (Array.isArray(candidate.evidence) && Array.isArray(candidate.references)) { const integrity = validateCitationIntegrity(candidate as ResearchResponse<unknown>); if (!integrity.valid) return { content: [{ type: 'text' as const, text: `Citation integrity failure: ${integrity.errors.join('; ')}` }], structuredContent: { integrity } as Record<string, unknown>, isError: true }; } return { content: [{ type: 'text' as const, text: summary }], structuredContent: data as Record<string, unknown> }; };
const extractionEvidence = (id: string, sourceId: string, title: string, text: string, locator: Locator) => ({ evidenceId: id, sourceId, authors: [], title, identifiers: {}, locator, evidenceType: 'DERIVED' as const, sourceQuality: 'C' as const, evidence: text, citationText: `${sourceId}${typeof locator.section === 'string' ? `#${locator.section}` : ''}` });
export function registerTools(server: McpServer, research: ResearchService): void {
  server.registerTool('search_papers', { title: 'Search papers', description: 'Search verified scholarly metadata across arXiv and Crossref. Results include provenance and transparent ranking.', inputSchema: z.object({ query: z.string().min(1), limit: z.number().int().min(1).max(50).default(10), year_from: z.number().int().optional(), year_to: z.number().int().optional(), author: z.string().optional(), venue: z.string().optional(), topic: z.string().optional() }) }, async ({query, limit, year_from, year_to, author, venue, topic}) => { const r = await research.search(query, limit, { ...(year_from===undefined?{}:{yearFrom:year_from}), ...(year_to===undefined?{}:{yearTo:year_to}), ...(author===undefined?{}:{author}), ...(venue===undefined?{}:{venue}), ...(topic===undefined?{}:{topic}) }); return result(r, r.summary); });
  server.registerTool('get_references', { title:'Get references', description:'Retrieve Semantic Scholar references with provenance.', inputSchema:z.object({paper_id:z.string().min(1),limit:z.number().int().min(1).max(100).default(20)}) }, async ({paper_id,limit}) => { const r=await research.graphAll(paper_id,'reference',limit); return result(r,r.summary); });
  server.registerTool('get_citations', { title:'Get citations', description:'Retrieve Semantic Scholar citing works with provenance.', inputSchema:z.object({paper_id:z.string().min(1),limit:z.number().int().min(1).max(100).default(20)}) }, async ({paper_id,limit}) => { const r=await research.graphAll(paper_id,'citation',limit); return result(r,r.summary); });
  server.registerTool('get_related_papers', { title:'Get related papers', description:'Retrieve Semantic Scholar recommendations with provenance.', inputSchema:z.object({paper_id:z.string().min(1),limit:z.number().int().min(1).max(100).default(20)}) }, async ({paper_id,limit}) => { const r=await research.graphAll(paper_id,'related',limit); return result(r,r.summary); });
  server.registerTool('resolve_author', { title:'Resolve author', description:'Resolve a Semantic Scholar author profile and linked paper identifiers.', inputSchema:z.object({author_id:z.string().min(1)}) }, async ({author_id}) => { const profile=await research.resolveAuthor(author_id); if(!profile)return {content:[{type:'text' as const,text:'NOT_FOUND: no Semantic Scholar author profile was resolved.'}],isError:true}; return {content:[{type:'text' as const,text:`${profile.name} (${profile.authorId})`}],structuredContent:{author:profile}}; });
  server.registerTool('read_paper', { title: 'Read paper', description: 'Acquire and parse a bounded HTML paper document with section and reference boundaries.', inputSchema: z.object({ url: z.string().url().max(2048) }) }, async ({url}) => { try { const document = await research.readPaper(url); return {content:[{type:'text' as const,text:`Parsed ${document.sections.length} sections from ${document.url}.`}],structuredContent:document}; } catch (error) { return {content:[{type:'text' as const,text:`Paper acquisition/parsing failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('search_within_paper', { title: 'Search within paper', description: 'Search parsed paper chunks and return source-located matches.', inputSchema: z.object({ url: z.string().url().max(2048), query: z.string().min(1).max(500), limit: z.number().int().min(1).max(50).default(10) }) }, async ({url, query, limit}) => { try { const matches = await research.searchWithinPaper(url, query, limit); return {content:[{type:'text' as const,text:`Found ${matches.length} matching chunks.`}],structuredContent:{query,url,matches}}; } catch (error) { return {content:[{type:'text' as const,text:`Paper search failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('extract_paper_facts', { title: 'Extract paper facts', description: 'Extract deterministic heuristic facts with source locators; no unsupported values are inferred.', inputSchema: z.object({ url: z.string().url().max(2048) }) }, async ({url}) => { try { const facts = await research.extractPaperFacts(url); const evidence = facts.map((fact, index) => extractionEvidence(`fact-evidence-${index}`, fact.sourceUrl, `Heuristic ${fact.kind} fact`, fact.text, fact.locator)); const citations = evidence.map(item => item.citationText).join(' | '); return {content:[{type:'text' as const,text:`Extracted ${facts.length} heuristic paper facts.${citations ? ` Evidence: ${citations}` : ''}`}],structuredContent:{url,facts,evidence}}; } catch (error) { return {content:[{type:'text' as const,text:`Paper fact extraction failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('extract_paper_claims', { title: 'Extract paper claims', description: 'Persist heuristic paper claims and report explicit conflicts with prior claims.', inputSchema: z.object({ url: z.string().url().max(2048) }) }, async ({url}) => { try { const result = await research.extractPaperClaims(url); const evidence = result.claims.map(claim => claim.evidence); const citations = evidence.map(item => item.citationText).join(' | '); return {content:[{type:'text' as const,text:`Extracted ${result.claims.length} claims and ${result.conflicts.length} conflicts.${citations ? ` Evidence: ${citations}` : ''}`}],structuredContent:{url,...result,evidence}}; } catch (error) { return {content:[{type:'text' as const,text:`Paper claim extraction failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('extract_training_parameters', { title: 'Extract training parameters', description: 'Extract only explicitly labeled training values with source locators.', inputSchema: z.object({ url: z.string().url().max(2048) }) }, async ({url}) => { try { const parameters = await research.extractTrainingParameters(url); const evidence = parameters.map((parameter, index) => extractionEvidence(`parameter-evidence-${index}`, parameter.sourceUrl, `Explicit ${parameter.name} parameter`, parameter.value, parameter.locator)); const citations = evidence.map(item => item.citationText).join(' | '); return {content:[{type:'text' as const,text:`Extracted ${parameters.length} explicit training parameters.${citations ? ` Evidence: ${citations}` : ''}`}],structuredContent:{url,parameters,evidence}}; } catch (error) { return {content:[{type:'text' as const,text:`Training parameter extraction failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('get_paper', { title: 'Get paper', description: 'Retrieve a canonical research work by paper ID, DOI, or arXiv ID.', inputSchema: z.object({ paper_id: z.string().min(1) }) }, async ({paper_id}) => { const p = research.getPaper(paper_id); if (!p) return { content: [{type:'text' as const, text: 'NOT_FOUND: no verified paper exists for this identifier.'}], isError: true }; const e=makeEvidence(p.paperId,p,`Metadata identifies the work as “${p.title}”.`); return result({data: p, evidence: [e], references: [p]}, `${p.authors.map(a=>a.name).join(', ')} — ${p.title} ${e.citationText}`); });
  server.registerTool('extract_training_recipe', { title: 'Extract training recipe', description: 'Return only source-backed training parameters. Missing values are never guessed.', inputSchema: z.object({ paper_id: z.string().min(1) }) }, async ({paper_id}) => { const p = research.getPaper(paper_id); if (!p) return {content:[{type:'text' as const,text:'NOT_FOUND: paper is not in the local verified database.'}],isError:true}; const r = research.recipe(p); return result(r, r.summary); });
  server.registerTool('extract_training_recipe_from_url', { title: 'Extract training recipe from paper', description: 'Populate only explicitly reported training recipe fields from a paper URL.', inputSchema: z.object({ url: z.string().url().max(2048) }) }, async ({url}) => { try { const recipe = await research.recipeFromPaper(url); return {content:[{type:'text' as const,text:recipe.summary}],structuredContent:recipe}; } catch (error) { return {content:[{type:'text' as const,text:`Training recipe extraction failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('get_bibtex', { title: 'Get BibTeX', description: 'Return canonical BibTeX without fabricating absent metadata.', inputSchema: z.object({paper_id:z.string().min(1)}) }, async ({paper_id}) => { const p=research.getPaper(paper_id); if(!p) return {content:[{type:'text' as const,text:'NOT_FOUND'}],isError:true}; const e=makeEvidence(p.paperId,p,`Metadata identifies the work as “${p.title}”.`); return result({bibtex:p.bibtex, paper:p, evidence:[e], references:[p]}, `${p.bibtex}\n${e.citationText}`); });
  server.registerTool('compare_papers', { title:'Compare papers', description:'Compare verified local paper metadata; benchmark comparability stays explicit when evidence is absent.', inputSchema:z.object({left_paper_id:z.string().min(1),right_paper_id:z.string().min(1)}) }, async ({left_paper_id,right_paper_id}) => { try { const r=await research.comparePapers(left_paper_id,right_paper_id); return result(r,r.summary); } catch (error) { return {content:[{type:'text' as const,text:`Paper comparison failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('verify_claim', { title:'Verify claim', description:'Resolve a persisted claim and report its current evidence status without upgrading derived evidence.', inputSchema:z.object({claim_id:z.string().min(1).max(200)}) }, async ({claim_id}) => { try { const r=await research.verifyClaim(claim_id); return {content:[{type:'text' as const,text:r.summary}],structuredContent:r}; } catch (error) { return {content:[{type:'text' as const,text:`Claim verification failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('compare_methods', { title:'Compare methods', description:'Compare two bounded method searches and report verified paper overlap without inferring benchmark equivalence.', inputSchema:z.object({left_method:z.string().min(1).max(500),right_method:z.string().min(1).max(500),limit:z.number().int().min(1).max(50).default(10)}) }, async ({left_method,right_method,limit}) => { try { const r=await research.compareMethods(left_method,right_method,limit); return result(r,r.summary); } catch (error) { return {content:[{type:'text' as const,text:`Method comparison failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('compare_paper_to_code', { title:'Compare paper to code', description:'Compare an explicit paper recipe with extracted revision-pinned repository configuration; repository content is never executed.', inputSchema:z.object({recipe:z.record(z.string(),z.unknown()),fields:z.array(z.object({name:z.string().min(1).max(200),value:z.string().max(500),lineStart:z.number().int().min(1),lineEnd:z.number().int().min(1)})).max(100),source_url:z.string().url().max(2000),commit_sha:z.string().max(200).optional()}) }, async ({recipe,fields,source_url,commit_sha}) => { const comparison=research.compareRecipeToConfig(recipe as any,fields,{url:source_url,...(commit_sha ? {commitSha:commit_sha} : {})}); return {content:[{type:'text' as const,text:`Paper/code comparison: ${comparison.conflicts.length} conflict(s), ${comparison.matches.length} match(es), ${comparison.unavailable.length} unavailable field(s).`}],structuredContent:{data:comparison}}; });
  server.registerTool('create_collection', { title:'Create collection', description:'Create or retrieve a persistent local paper collection.', inputSchema:z.object({name:z.string().min(1).max(200)}) }, async ({name}) => { try { const collection=research.createCollection(name); return {content:[{type:'text' as const,text:`Collection ${collection.name} (${collection.id})`}],structuredContent:{collection}}; } catch(error) { return {content:[{type:'text' as const,text:`Collection creation failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('list_collections', { title:'List collections', description:'List persistent local paper collections and their memberships.', inputSchema:z.object({}) }, async () => { return {content:[{type:'text' as const,text:`Found ${research.listCollections().length} collection(s).`}],structuredContent:{collections:research.listCollections()}}; });
  server.registerTool('add_paper_to_collection', { title:'Add paper to collection', description:'Add an existing verified paper to a persistent local collection.', inputSchema:z.object({collection_id:z.string().min(1).max(200),paper_id:z.string().min(1).max(500)}) }, async ({collection_id,paper_id}) => { try { research.addToCollection(collection_id,paper_id); return {content:[{type:'text' as const,text:'Paper added to collection.'}],structuredContent:{collectionId:collection_id,paperId:paper_id}}; } catch(error) { return {content:[{type:'text' as const,text:`Collection membership failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('remove_paper_from_collection', { title:'Remove paper from collection', description:'Remove a paper from a persistent local collection without deleting the paper.', inputSchema:z.object({collection_id:z.string().min(1).max(200),paper_id:z.string().min(1).max(500)}) }, async ({collection_id,paper_id}) => { try { research.removeFromCollection(collection_id,paper_id); return {content:[{type:'text' as const,text:'Paper removed from collection.'}],structuredContent:{collectionId:collection_id,paperId:paper_id}}; } catch(error) { return {content:[{type:'text' as const,text:`Collection removal failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('delete_collection', { title:'Delete collection', description:'Delete a persistent local collection and its memberships without deleting papers.', inputSchema:z.object({collection_id:z.string().min(1).max(200)}) }, async ({collection_id}) => { try { research.deleteCollection(collection_id); return {content:[{type:'text' as const,text:'Collection deleted.'}],structuredContent:{collectionId:collection_id}}; } catch(error) { return {content:[{type:'text' as const,text:`Collection deletion failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('export_research_pack', { title:'Export ResearchPack', description:'Export a deterministic local collection ResearchPack without remote calls.', inputSchema:z.object({collection_id:z.string().min(1).max(200)}) }, async ({collection_id}) => { try { const pack=research.buildResearchPack(collection_id); return {content:[{type:'text' as const,text:`Exported ${pack.papers.length} paper(s) from ${pack.collection.name}.`}],structuredContent:pack}; } catch(error) { return {content:[{type:'text' as const,text:`ResearchPack export failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('import_research_pack', { title:'Import ResearchPack', description:'Import a bounded JSON ResearchPack as untrusted static metadata; no code is executed.', inputSchema:z.object({pack_json:z.string().min(2).max(2000000)}) }, async ({pack_json}) => { try { const pack=JSON.parse(pack_json); const collection=research.importResearchPack(pack); return {content:[{type:'text' as const,text:`Imported ${collection.paperIds.length} paper(s) into ${collection.name}.`}],structuredContent:{collection}}; } catch(error) { return {content:[{type:'text' as const,text:`ResearchPack import failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('refresh_paper', { title:'Refresh paper', description:'Refresh locally stored metadata through an available provider-native identifier.', inputSchema:z.object({paper_id:z.string().min(1).max(500)}) }, async ({paper_id}) => { try { const outcome=await research.refreshPaper(paper_id); return {content:[{type:'text' as const,text:`Paper refresh ${outcome.status}.`}],structuredContent:outcome,isError:outcome.status==='FAILED'}; } catch(error) { return {content:[{type:'text' as const,text:`Paper refresh failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('refresh_collection', { title:'Refresh collection', description:'Refresh locally stored metadata for every paper in a collection, preserving per-paper outcomes.', inputSchema:z.object({collection_id:z.string().min(1).max(200)}) }, async ({collection_id}) => { try { const outcomes=await research.refreshCollection(collection_id); return {content:[{type:'text' as const,text:`Refreshed ${outcomes.filter(item=>item.status==='REFRESHED').length} paper(s); ${outcomes.filter(item=>item.status!=='REFRESHED').length} unavailable or failed.`}],structuredContent:{collectionId:collection_id,outcomes}}; } catch(error) { return {content:[{type:'text' as const,text:`Collection refresh failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('research_method', { title:'Research method', description:'Search verified literature for a named method with provider transparency and evidence.', inputSchema:z.object({method:z.string().min(1).max(500),limit:z.number().int().min(1).max(50).default(10)}) }, async ({method,limit}) => { const r=await research.researchMethod(method,limit); return result(r,r.summary); });
  server.registerTool('build_research_report', { title:'Build research report', description:'Build a cited literature, implementation, or reproducibility report with facts and recommendations separated.', inputSchema:z.object({query:z.string().min(1).max(500),mode:z.enum(['literature_review','implementation','reproducibility']).default('literature_review'),limit:z.number().int().min(1).max(50).default(15)}) }, async ({query,mode,limit}) => { try { const r=await research.buildResearchReport(query,mode,limit); return result(r,r.summary); } catch (error) { return {content:[{type:'text' as const,text:`Research report failed: ${String(error)}`}],isError:true}; } });
  server.registerTool('research_topic', { title: 'Research topic', description: 'Build a provenance-preserving literature overview. Synthesis is labeled; no unsupported claims are emitted.', inputSchema: z.object({topic:z.string().min(1), objective:z.enum(['implement','literature_review']).default('literature_review'), depth:z.enum(['quick','deep']).default('quick'), limit:z.number().int().min(1).max(50).default(15)}) }, async ({topic, limit}) => { const r=await research.search(topic,limit); return result({...r, synthesis: r.data.length ? `Retrieved ${r.data.length} works for the topic. This is a retrieval result, not an assertion that the works use identical methods.` : 'No verified literature was retrieved.'}, r.summary); });
  registerEcosystemTools(server, { research });
 }
