import { DatabaseSync } from 'node:sqlite';
import { createHash } from 'node:crypto';
import type { ResearchWork, Evidence, GraphEdge } from '../models/research.js';
import type { ParsedDocument } from '../ingestion/document.js';
import type { PaperClaim, ClaimConflict } from '../extraction/claims.js';
import { runMigrations } from './migrations.js';
import type { AsyncResearchStore } from './store.js';

export interface Collection { id:string; name:string; paperIds:string[]; }

export class ResearchDb implements AsyncResearchStore {
  private db: DatabaseSync;
  constructor(path = process.env.RESEARCH_DB_PATH ?? ':memory:') { this.db = new DatabaseSync(path); this.db.exec('PRAGMA journal_mode = WAL;'); runMigrations(this.db); }
  schemaVersion():number { const row=this.db.prepare('SELECT COALESCE(MAX(version),0) AS version FROM schema_migrations').get() as {version:number}; return row.version; }
  async upsertWork(work: ResearchWork): Promise<void> { this.db.prepare('INSERT INTO works(paper_id,data,title,doi,arxiv_id,year) VALUES(?,?,?,?,?,?) ON CONFLICT(paper_id) DO UPDATE SET data=excluded.data,title=excluded.title,doi=excluded.doi,arxiv_id=excluded.arxiv_id,year=excluded.year').run(work.paperId, JSON.stringify(work), work.title, work.doi ?? null, work.arxivId ?? null, work.year ?? null); this.db.prepare('DELETE FROM works_fts WHERE paper_id=?').run(work.paperId); this.db.prepare('INSERT INTO works_fts(paper_id,title,abstract) VALUES(?,?,?)').run(work.paperId, work.title, work.abstract ?? ''); }
  async addEvidence(e: Evidence, paperId: string): Promise<void> { this.db.prepare('INSERT OR REPLACE INTO evidence(evidence_id,source_id,paper_id,data) VALUES(?,?,?,?)').run(e.evidenceId, e.sourceId, paperId, JSON.stringify(e)); }
  async upsertGraphEdge(edge: GraphEdge): Promise<void> { this.db.prepare('INSERT INTO graph_edges(source_paper_id,target_paper_id,relation,relationship_class,provider,evidence_id,retrieved_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(source_paper_id,target_paper_id,relation,provider) DO UPDATE SET relationship_class=excluded.relationship_class,evidence_id=excluded.evidence_id,retrieved_at=excluded.retrieved_at').run(edge.sourcePaperId,edge.targetPaperId,edge.relation,edge.relationshipClass,edge.provider,edge.evidenceId,edge.retrievedAt); }
  async getGraphEdges(sourcePaperId?: string): Promise<GraphEdge[]> { const rows = (sourcePaperId ? this.db.prepare('SELECT source_paper_id AS sourcePaperId,target_paper_id AS targetPaperId,relation,relationship_class AS relationshipClass,provider,evidence_id AS evidenceId,retrieved_at AS retrievedAt FROM graph_edges WHERE source_paper_id=?') : this.db.prepare('SELECT source_paper_id AS sourcePaperId,target_paper_id AS targetPaperId,relation,relationship_class AS relationshipClass,provider,evidence_id AS evidenceId,retrieved_at AS retrievedAt FROM graph_edges')).all(...(sourcePaperId ? [sourcePaperId] : [])) as unknown as GraphEdge[]; return rows; }
  async getWork(id: string): Promise<ResearchWork | undefined> { const row = this.db.prepare('SELECT data FROM works WHERE paper_id=? OR doi=? OR arxiv_id=?').get(id, id, id) as {data: string} | undefined; return row ? JSON.parse(row.data) as ResearchWork : undefined; }
  async search(query: string, limit = 20): Promise<ResearchWork[]> { const rows = this.db.prepare('SELECT data FROM works WHERE paper_id IN (SELECT paper_id FROM works_fts WHERE works_fts MATCH ? LIMIT ?)').all(query.replace(/["']/g, ' '), limit) as {data: string}[]; return rows.map(r => JSON.parse(r.data) as ResearchWork); }
  async saveParsedDocument(document: ParsedDocument, contentHash: string): Promise<void> { this.db.prepare('INSERT OR REPLACE INTO parsed_documents(url,content_hash,data,retrieved_at) VALUES(?,?,?,?)').run(document.url, contentHash, JSON.stringify(document), new Date().toISOString()); }
  async getParsedDocument(url: string, contentHash: string): Promise<ParsedDocument | undefined> { const row = this.db.prepare('SELECT data FROM parsed_documents WHERE url=? AND content_hash=?').get(url, contentHash) as {data:string} | undefined; return row ? JSON.parse(row.data) as ParsedDocument : undefined; }
  async saveClaim(claim: PaperClaim): Promise<void> { this.db.prepare('INSERT OR REPLACE INTO paper_claims(claim_id,claim_key,data) VALUES(?,?,?)').run(claim.claimId, claim.claimKey, JSON.stringify(claim)); await this.addEvidence(claim.evidence, claim.claimId); }
  async getClaims(): Promise<PaperClaim[]> { return (this.db.prepare('SELECT data FROM paper_claims ORDER BY claim_id').all() as {data:string}[]).map(row => JSON.parse(row.data) as PaperClaim); }
  async getClaim(claimId: string): Promise<PaperClaim | undefined> { const row=this.db.prepare('SELECT data FROM paper_claims WHERE claim_id=?').get(claimId) as {data:string}|undefined; return row ? JSON.parse(row.data) as PaperClaim : undefined; }
  async getEvidenceForPaper(paperId: string): Promise<Evidence[]> { return (this.db.prepare('SELECT data FROM evidence WHERE paper_id=? ORDER BY evidence_id').all(paperId) as {data:string}[]).map(row => JSON.parse(row.data) as Evidence); }
  async createCollection(name:string): Promise<Collection> { const normalized=name.trim(); if(!normalized) throw new Error('collection name must not be empty'); const id=`collection-${createHash('sha256').update(normalized.normalize('NFKC').toLowerCase()).digest('hex').slice(0,24)}`; this.db.prepare('INSERT OR IGNORE INTO collections(collection_id,name) VALUES(?,?)').run(id,normalized); return (await this.getCollection(id))!; }
  async addToCollection(collectionId:string,paperId:string): Promise<void> { this.db.prepare('INSERT OR IGNORE INTO collection_items(collection_id,paper_id) VALUES(?,?)').run(collectionId,paperId); }
  async removeFromCollection(collectionId:string,paperId:string):Promise<void> { this.db.prepare('DELETE FROM collection_items WHERE collection_id=? AND paper_id=?').run(collectionId,paperId); }
  async deleteCollection(collectionId:string):Promise<void> { this.db.prepare('DELETE FROM collection_items WHERE collection_id=?').run(collectionId); this.db.prepare('DELETE FROM collections WHERE collection_id=?').run(collectionId); }
  async getCollection(collectionId:string): Promise<Collection|undefined> { const row=this.db.prepare('SELECT collection_id AS id,name FROM collections WHERE collection_id=?').get(collectionId) as {id:string;name:string}|undefined; if(!row)return undefined; const items=this.db.prepare('SELECT paper_id AS paperId FROM collection_items WHERE collection_id=? ORDER BY paper_id').all(collectionId) as {paperId:string}[]; return {id:row.id,name:row.name,paperIds:items.map(item=>item.paperId)}; }
  async listCollections(): Promise<Collection[]> { return (this.db.prepare('SELECT collection_id AS id,name FROM collections ORDER BY name,id').all() as {id:string;name:string}[]).map(row=>({id:row.id,name:row.name,paperIds:(this.db.prepare('SELECT paper_id AS paperId FROM collection_items WHERE collection_id=? ORDER BY paper_id').all(row.id) as {paperId:string}[]).map(item=>item.paperId)})); }
  async saveClaimConflict(conflict: ClaimConflict): Promise<void> { this.db.prepare('INSERT OR REPLACE INTO claim_conflicts(claim_key,selected_claim_id,alternate_claim_id,data) VALUES(?,?,?,?)').run(conflict.claimKey, conflict.selectedClaimId, conflict.alternateClaimId, JSON.stringify(conflict)); }
  async getClaimConflicts(): Promise<ClaimConflict[]> { return (this.db.prepare('SELECT data FROM claim_conflicts ORDER BY claim_key,selected_claim_id,alternate_claim_id').all() as {data:string}[]).map(row => JSON.parse(row.data) as ClaimConflict); }
  async close(): Promise<void> { this.db.close(); }
}
