import { DatabaseSync } from 'node:sqlite';
import type { ResearchWork, Evidence, GraphEdge } from '../models/research.js';

export class ResearchDb {
  private db: DatabaseSync;
  constructor(path = process.env.RESEARCH_DB_PATH ?? ':memory:') { this.db = new DatabaseSync(path); this.db.exec('PRAGMA journal_mode = WAL; CREATE TABLE IF NOT EXISTS works (paper_id TEXT PRIMARY KEY, data TEXT NOT NULL, title TEXT NOT NULL, doi TEXT, arxiv_id TEXT, year INTEGER); CREATE TABLE IF NOT EXISTS evidence (evidence_id TEXT PRIMARY KEY, source_id TEXT NOT NULL, paper_id TEXT NOT NULL, data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS graph_edges (source_paper_id TEXT NOT NULL, target_paper_id TEXT NOT NULL, relation TEXT NOT NULL, relationship_class TEXT NOT NULL DEFAULT \'DIRECT\', provider TEXT NOT NULL, evidence_id TEXT NOT NULL, retrieved_at TEXT NOT NULL, PRIMARY KEY(source_paper_id,target_paper_id,relation,provider)); CREATE VIRTUAL TABLE IF NOT EXISTS works_fts USING fts5(paper_id UNINDEXED, title, abstract);'); try { this.db.exec("ALTER TABLE graph_edges ADD COLUMN relationship_class TEXT NOT NULL DEFAULT 'DIRECT'"); } catch { /* existing schema already migrated */ } }
  upsertWork(work: ResearchWork): void { this.db.prepare('INSERT INTO works(paper_id,data,title,doi,arxiv_id,year) VALUES(?,?,?,?,?,?) ON CONFLICT(paper_id) DO UPDATE SET data=excluded.data,title=excluded.title,doi=excluded.doi,arxiv_id=excluded.arxiv_id,year=excluded.year').run(work.paperId, JSON.stringify(work), work.title, work.doi ?? null, work.arxivId ?? null, work.year ?? null); this.db.prepare('DELETE FROM works_fts WHERE paper_id=?').run(work.paperId); this.db.prepare('INSERT INTO works_fts(paper_id,title,abstract) VALUES(?,?,?)').run(work.paperId, work.title, work.abstract ?? ''); }
  addEvidence(e: Evidence, paperId: string): void { this.db.prepare('INSERT OR REPLACE INTO evidence(evidence_id,source_id,paper_id,data) VALUES(?,?,?,?)').run(e.evidenceId, e.sourceId, paperId, JSON.stringify(e)); }
  upsertGraphEdge(edge: GraphEdge): void { this.db.prepare('INSERT INTO graph_edges(source_paper_id,target_paper_id,relation,relationship_class,provider,evidence_id,retrieved_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(source_paper_id,target_paper_id,relation,provider) DO UPDATE SET relationship_class=excluded.relationship_class,evidence_id=excluded.evidence_id,retrieved_at=excluded.retrieved_at').run(edge.sourcePaperId,edge.targetPaperId,edge.relation,edge.relationshipClass,edge.provider,edge.evidenceId,edge.retrievedAt); }
  getGraphEdges(sourcePaperId?: string): GraphEdge[] { const rows = (sourcePaperId ? this.db.prepare('SELECT source_paper_id AS sourcePaperId,target_paper_id AS targetPaperId,relation,relationship_class AS relationshipClass,provider,evidence_id AS evidenceId,retrieved_at AS retrievedAt FROM graph_edges WHERE source_paper_id=?') : this.db.prepare('SELECT source_paper_id AS sourcePaperId,target_paper_id AS targetPaperId,relation,relationship_class AS relationshipClass,provider,evidence_id AS evidenceId,retrieved_at AS retrievedAt FROM graph_edges')).all(...(sourcePaperId ? [sourcePaperId] : [])) as unknown as GraphEdge[]; return rows; }
  getWork(id: string): ResearchWork | undefined { const row = this.db.prepare('SELECT data FROM works WHERE paper_id=? OR doi=? OR arxiv_id=?').get(id, id, id) as {data: string} | undefined; return row ? JSON.parse(row.data) as ResearchWork : undefined; }
  search(query: string, limit = 20): ResearchWork[] { const rows = this.db.prepare('SELECT data FROM works WHERE paper_id IN (SELECT paper_id FROM works_fts WHERE works_fts MATCH ? LIMIT ?)').all(query.replace(/["']/g, ' '), limit) as {data: string}[]; return rows.map(r => JSON.parse(r.data) as ResearchWork); }
  close(): void { this.db.close(); }
}
