import { z } from 'zod/v4';
import { McpServer } from '@modelcontextprotocol/server';
import { HuggingFaceProvider } from '../../providers/huggingface.js';
import type { ResearchService } from '../../research/service.js';
import { extractConfigFields } from '../../research/config-extraction.js';
import { GitHubProvider, decodeGitHubContent } from '../../providers/github.js';

export interface EcosystemToolDependencies { github?: GitHubProvider; huggingface?: HuggingFaceProvider; research?: ResearchService; }
export function registerEcosystemTools(server: McpServer, dependencies: EcosystemToolDependencies = {}): void {
  const github = dependencies.github ?? new GitHubProvider();
  const huggingface = dependencies.huggingface ?? new HuggingFaceProvider();
  const research = dependencies.research;
  server.registerTool('find_implementations', { title: 'Find implementations', description: 'Find GitHub repositories related to a verified paper or method. Status is UNKNOWN unless separately verified.', inputSchema: z.object({method:z.string().min(1).optional(), paper_id:z.string().min(1).optional(), limit:z.number().int().min(1).max(20).default(10)}).refine(x=>Boolean(x.method||x.paper_id),{message:'Provide method or paper_id'}) }, async ({method, paper_id, limit}) => { const paper=paper_id ? research?.getPaper(paper_id) : undefined; if(paper_id&&!paper) return {content:[{type:'text' as const,text:'NOT_FOUND: paper is not in the local verified database.'}],isError:true}; const query=method ?? paper?.title; if(!query) return {content:[{type:'text' as const,text:'INVALID_INPUT: provide method or paper_id.'}],isError:true}; const data=await github.searchRepositories(query,limit); return {content:[{type:'text' as const,text:data.length ? data.map(x=>`${x.fullName} — ${x.htmlUrl} [${x.implementationStatus}]`).join('\\n') : 'No repositories found. GitHub search is not evidence that a repository is official.'}],structuredContent:{data,source:'github',searchQuery:query,linkedPaper:paper?{title:paper.title,identifiers:{doi:paper.doi,arxiv:paper.arxivId,semanticScholar:paper.semanticScholarId,openAlex:paper.openAlexId}}:null,implementationStatusPolicy:'UNKNOWN until paper or author linkage is verified.'}}; });
  server.registerTool('find_models', { title: 'Find Hugging Face models', description: 'Find model repositories on Hugging Face, including revision and card metadata when available.', inputSchema: z.object({query:z.string().min(1), limit:z.number().int().min(1).max(20).default(10)}) }, async ({query, limit}) => { const data=await huggingface.searchModels(query,limit); return {content:[{type:'text' as const,text:data.length ? data.map(x=>`${x.id} — ${x.url}${x.sha ? ` (revision ${x.sha})` : ''}`).join('\\n') : 'No verified model repositories found.'}],structuredContent:{data,source:'huggingface'}}; });
  server.registerTool('find_repository_configs', { title: 'Find repository configs', description: 'List common configuration files at a repository revision without executing or recursively crawling repository content.', inputSchema: z.object({owner:z.string().regex(/^[A-Za-z0-9_.-]+$/), repo:z.string().regex(/^[A-Za-z0-9_.-]+$/), ref:z.string().max(100).optional()}) }, async ({owner,repo,ref}) => { const revision=ref ? await github.resolveRevision(owner,repo,ref) : undefined; const entries=await github.listContents(owner,repo,'',ref); const names=new Set(['config.yaml','config.yml','training.yaml','training.yml','train.yaml','train.yml','args.yaml','params.yaml','pyproject.toml','training_config.json']); const data=entries.filter(x=>x.type==='file'&&names.has(x.name)).map(x=>({...x,requestedRevision:ref ?? null,commitSha:revision ?? null})); return {content:[{type:'text' as const,text:data.length ? data.map(x=>`${x.path} — ${x.htmlUrl ?? 'no URL'}${x.commitSha ? ` (commit ${x.commitSha})` : ''}`).join('\\n') : 'No common configuration files found at the requested repository root.'}],structuredContent:{repository:`${owner}/${repo}`,requestedRevision:ref ?? null,commitSha:revision ?? null,data,source:'github'}}; });
 server.registerTool('get_repository_config', { title: 'Get repository config', description: 'Read a repository file statically at an optional revision. Repository content is never executed.', inputSchema: z.object({owner:z.string().regex(/^[A-Za-z0-9_.-]+$/), repo:z.string().regex(/^[A-Za-z0-9_.-]+$/), path:z.string().min(1).max(256).refine(p=>!p.includes('..') && !p.startsWith('/')), ref:z.string().max(100).optional()}) }, async ({owner,repo,path,ref}) => { const file=await github.getContent(owner,repo,path,ref); if(!file) return {content:[{type:'text' as const,text:'NOT_FOUND: repository file unavailable.'}],isError:true}; const text=decodeGitHubContent(file); if(text===undefined) return {content:[{type:'text' as const,text:'SOURCE_UNAVAILABLE: GitHub returned no decodable file content.'}],isError:true}; const numbered=text.split('\\n').map((line,index)=>`${index+1}: ${line}`).join('\\n'); const extracted=extractConfigFields(text,path); return {content:[{type:'text' as const,text:`${file.repository}/${file.path}\\n${numbered}`}],structuredContent:{repository:file.repository,path:file.path,blobSha:file.sha,requestedRevision:ref ?? null,content:text,lines:text.split('\\n').length,fields:extracted.fields,parserWarnings:extracted.warnings,source:{type:'github',url:file.htmlUrl ?? file.downloadUrl ?? null,commitSha:file.commitSha ?? null}}}; });
}
