import type { StructuredLogger } from './logger.js';

export type CacheEntry = { status:number; headers:Record<string,string>; body:string; expiresAt:number };
export interface DurableResponseCache { get(key:string):Promise<CacheEntry|undefined>; set(key:string,entry:CacheEntry):Promise<void>; delete?(key:string):Promise<void>; close?():Promise<void>; }
export type ReliabilityEvent = { type: 'cache_hit' | 'request' | 'retry' | 'success' | 'failure'; url: string; attempt?: number; status?: number; delayMs?: number; durationMs?: number };
export type LatencyHistogram = { count:number; minMs:number; maxMs:number; buckets:{le10:number;le50:number;le100:number;le250:number;le1000:number;over1000:number}; };
export interface ReliabilityStats { requests: number; cacheHits: number; retries: number; successes: number; failures: number; totalLatencyMs: number; lastLatencyMs?: number; providerLatency: Record<string,LatencyHistogram>; }
export interface ReliableFetcherOptions { cacheTtlMs?: number; minIntervalMs?: number; maxRetries?: number; baseDelayMs?: number; sleep?: (ms:number)=>Promise<void>; now?: ()=>number; onEvent?: (event:ReliabilityEvent)=>void; durableCache?: DurableResponseCache; logger?: StructuredLogger; }
export class RequestCache {
  private readonly values=new Map<string,{response:Response;expiresAt:number}>();
  constructor(private readonly ttlMs:number,private readonly now=()=>Date.now(),private readonly maxEntries=1000){}
  get(key:string):Response|undefined { const entry=this.values.get(key); if(!entry)return undefined; if(entry.expiresAt<=this.now()){this.values.delete(key);return undefined;} return entry.response.clone(); }
  set(key:string,response:Response):void { if(this.ttlMs<=0)return; this.prune(); while(this.values.size>=this.maxEntries)this.values.delete(this.values.keys().next().value!); this.values.set(key,{response:response.clone(),expiresAt:this.now()+this.ttlMs}); }
  private prune():void { const now=this.now(); for(const [key,entry] of this.values)if(entry.expiresAt<=now)this.values.delete(key); }
}
type LimiterState={nextAllowedAt:number;lastNow:number;tail:Promise<void>};
async function waitForRateLimit(host:string,minInterval:number,sleep:(ms:number)=>Promise<void>,now:()=>number,limiters:Map<string,LimiterState>):Promise<()=>void> { const state=limiters.get(host)??{nextAllowedAt:0,lastNow:0,tail:Promise.resolve()}; limiters.set(host,state); const previous=state.tail; let releaseQueue!:()=>void; state.tail=new Promise(resolve=>{releaseQueue=resolve;}); await previous; const currentNow=now(); if(currentNow<state.lastNow-1_000_000)state.nextAllowedAt=currentNow; state.lastNow=currentNow; const wait=Math.max(0,state.nextAllowedAt-currentNow); if(wait>0)await sleep(wait); state.nextAllowedAt=now()+minInterval; state.lastNow=state.nextAllowedAt; return releaseQueue; }
const emptyHistogram=():LatencyHistogram=>({count:0,minMs:Number.POSITIVE_INFINITY,maxMs:0,buckets:{le10:0,le50:0,le100:0,le250:0,le1000:0,over1000:0}});
const stats:ReliabilityStats={requests:0,cacheHits:0,retries:0,successes:0,failures:0,totalLatencyMs:0,providerLatency:{}};
export function getReliabilityStats():ReliabilityStats { return { ...stats, providerLatency:Object.fromEntries(Object.entries(stats.providerLatency).map(([provider,histogram])=>[provider,{...histogram,buckets:{...histogram.buckets}}])) }; }
function providerFor(url:string):string { try{return new URL(url).hostname;}catch{return 'unknown';} }
function recordLatency(url:string,durationMs:number):void { stats.totalLatencyMs+=durationMs;stats.lastLatencyMs=durationMs;const provider=providerFor(url);const histogram=stats.providerLatency[provider]??emptyHistogram();histogram.count++;histogram.minMs=Math.min(histogram.minMs,durationMs);histogram.maxMs=Math.max(histogram.maxMs,durationMs);if(durationMs<=10)histogram.buckets.le10++;else if(durationMs<=50)histogram.buckets.le50++;else if(durationMs<=100)histogram.buckets.le100++;else if(durationMs<=250)histogram.buckets.le250++;else if(durationMs<=1000)histogram.buckets.le1000++;else histogram.buckets.over1000++;stats.providerLatency[provider]=histogram; }
function emit(event:ReliabilityEvent,callback?: (event:ReliabilityEvent)=>void,logger?:StructuredLogger):void { if(event.type==='request')stats.requests++; else if(event.type==='cache_hit')stats.cacheHits++; else if(event.type==='retry')stats.retries++; else if(event.type==='success')stats.successes++; else if(event.type==='failure')stats.failures++; if(event.durationMs!==undefined)recordLatency(event.url,event.durationMs); callback?.(event); const level=event.type==='failure'?'error':event.type==='retry'?'warn':event.type==='success'?'info':'debug'; logger?.[level](`provider_${event.type}`,{url:event.url,attempt:event.attempt,status:event.status,delayMs:event.delayMs,durationMs:event.durationMs}); }
const entryToResponse=(entry:CacheEntry):Response=>new Response(entry.body,{status:entry.status,headers:entry.headers});
async function responseToEntry(response:Response,expiresAt:number):Promise<CacheEntry>{const headers:Record<string,string>={};response.headers.forEach((value,key)=>{headers[key]=value;});return {status:response.status,headers,body:await response.clone().text(),expiresAt};}
function tryUrl(value:string):URL|undefined { try{return new URL(value);}catch{return undefined;} }
function isCacheSafe(url:URL|undefined,headers:Headers):boolean { if(!url||headers.has('authorization')||headers.has('cookie')||headers.has('proxy-authorization'))return false; return ![...url.searchParams.keys()].some(key=>/(?:token|secret|password|passwd|api[_-]?key|auth|credential|signature)/i.test(key)); }
function responseIsCacheSafe(response:Response):boolean { const cacheControl=response.headers.get('cache-control')??''; if(/(^|,)\s*(private|no-store|no-cache)\b/i.test(cacheControl)||response.headers.has('set-cookie'))return false; const vary=response.headers.get('vary')??''; return !vary.split(',').some(value=>/^(authorization|cookie|set-cookie|\*)$/i.test(value.trim())); }
 export function createReliableFetcher(fetcher: typeof fetch = fetch, options:ReliableFetcherOptions={}):typeof fetch {
  const cache=new RequestCache(options.cacheTtlMs ?? 30_000,options.now); const sleep=options.sleep ?? ((ms:number)=>new Promise(resolve=>setTimeout(resolve,ms))); const minInterval=options.minIntervalMs ?? 0; const maxRetries=options.maxRetries ?? 2; const baseDelay=options.baseDelayMs ?? 250; const inFlight=new Map<string,Promise<Response>>(); const limiters=new Map<string,LimiterState>(); const now=options.now ?? (()=>Date.now());
  const run=async (input:RequestInfo|URL,init?:RequestInit):Promise<Response>=>{
    const url=typeof input==='string'?input:input instanceof URL?input.toString():input.url; const method=(init?.method ?? (input instanceof Request ? input.method : 'GET')).toUpperCase(); const requestHeaders=new Headers(init?.headers ?? (input instanceof Request ? input.headers : undefined)); const parsedUrl=tryUrl(url); const cacheable=method==='GET'&&isCacheSafe(parsedUrl,requestHeaders); const headerKey=[...requestHeaders.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([key,value])=>`${key}=${value}`).join('&'); const key=`${method}:${url}:${headerKey}`;
    if(cacheable){ const cached=cache.get(key); if(cached){emit({type:'cache_hit',url},options.onEvent,options.logger);return cached;} if(options.durableCache){try{const durable=await options.durableCache.get(key);if(durable&&durable.expiresAt>now()){const response=entryToResponse(durable);cache.set(key,response);emit({type:'cache_hit',url},options.onEvent,options.logger);return response;}if(durable)await options.durableCache.delete?.(key);}catch{ /* corrupted/unavailable cache must not block research */ }} const existing=inFlight.get(key); if(existing)return (await existing).clone(); }
    const operation=(async()=>{ for(let attempt=0;;attempt++){ const release=await waitForRateLimit(parsedUrl?.hostname??'unknown',minInterval,sleep,now,limiters); emit({type:'request',url,attempt},options.onEvent,options.logger); const startedAt=now(); let result:Response; try { result=await fetcher(input,init); } catch(error) { const durationMs=now()-startedAt; if(attempt<maxRetries){ const delay=Math.min(30_000,baseDelay*2**attempt); release(); emit({type:'retry',url,attempt,delayMs:delay},options.onEvent,options.logger); await sleep(delay); continue; } emit({type:'failure',url,attempt,durationMs},options.onEvent,options.logger); release(); throw error; } const durationMs=now()-startedAt; if((result.status===429||result.status>=500)&&attempt<maxRetries){ const retryAfter=result.headers.get('retry-after'); const seconds=retryAfter ? Number(retryAfter) : NaN; const retryDate=retryAfter && !Number.isFinite(seconds) ? Date.parse(retryAfter) : NaN; const delay= Math.min(30_000, Number.isFinite(seconds)?Math.max(0,seconds*1000):Number.isFinite(retryDate)?Math.max(0,retryDate-now()):baseDelay*2**attempt); emit({type:'retry',url,attempt,status:result.status,delayMs:delay},options.onEvent,options.logger); release(); await sleep(delay); continue; } if(!result.ok){emit({type:'failure',url,attempt,status:result.status,durationMs},options.onEvent,options.logger);release();return result;} emit({type:'success',url,attempt,status:result.status,durationMs},options.onEvent,options.logger); release(); if(cacheable&&responseIsCacheSafe(result)){cache.set(key,result);if(options.durableCache&&options.cacheTtlMs&&options.cacheTtlMs>0)try{await options.durableCache.set(key,await responseToEntry(result,now()+options.cacheTtlMs));}catch{ /* durable cache is an optimization */ }} return result; } })();
    if(cacheable)inFlight.set(key,operation); try{return await operation;} finally{if(cacheable)inFlight.delete(key);}
  }; return run as typeof fetch;
}
