import type { ParsedDocument } from '../ingestion/document.js';
import type { Locator } from '../models/research.js';

export type PropositionField='objectives'|'objective'|'formulation'|'parallelism'|'architecture'|'partitioned_state'|'components'|'component'|'regimes'|'stages'|'attention'|'trace'|'parameter'|'method'|'algorithm'|'interaction'|'retriever'|'operator'|'context';
export interface ResearchProposition { field:PropositionField; value:string; sourceText:string; locator:Locator; rule:string; }
const rules:Array<[PropositionField,string,RegExp,string]>= [
 ['objectives','masked language model',/masked language model/i,'explicit objective phrase'],['objectives','next sentence prediction',/next sentence prediction/i,'explicit objective phrase'],['objectives','next-token prediction',/next[- ]token prediction/i,'explicit objective phrase'],
 ['objective','text infilling',/text infilling/i,'explicit denoising objective'],['objective','contrastive learning',/contrastive (?:learning|objective|loss)/i,'explicit contrastive objective'],['objective','span corruption',/span corruption/i,'explicit corruption objective'],
 ['formulation','text-to-text',/text[- ]to[- ]text/i,'explicit task formulation'],['formulation','draft-and-verify',/draft(?:ing)?[- ]and[- ]verif(?:y|ication)/i,'explicit decoding formulation'],['formulation','cross-attention',/cross[- ]attention/i,'explicit multimodal connection'],
 ['parallelism','tensor model parallelism',/tensor model parallel(?:ism)?/i,'explicit parallelism phrase'],['parallelism','data parallelism',/data parallel(?:ism)?/i,'explicit parallelism phrase'],['parallelism','pipeline model parallelism',/pipeline model parallel(?:ism)?/i,'explicit parallelism phrase'],['parallelism','tensor model parallelism',/intra[- ]layer model parallel(?:ism)?/i,'explicit tensor-parallel formulation'],
 ['architecture','sparse mixture of experts',/sparse mixture[- ]of[- ]experts|mixture[- ]of[- ]experts/i,'explicit sparse architecture'],['architecture','long convolutions',/long convolution/i,'explicit sequence operator'],
 ['partitioned_state','optimizer states',/optimizer states?/i,'explicit partitioned training state'],['partitioned_state','gradients',/\bgradients\b/i,'explicit partitioned training state'],['partitioned_state','parameters',/\bparameters\b/i,'explicit partitioned training state'],
 ['components','retriever',/\bretriever\b/i,'explicit retrieval component'],['components','generator',/\bgenerator\b/i,'explicit generation component'],['component','Q-Former',/Q[- ]Former/i,'explicit bridge module'],
 ['regimes','zero-shot',/zero[- ]shot/i,'explicit evaluation regime'],['regimes','one-shot',/one[- ]shot/i,'explicit evaluation regime'],['regimes','few-shot',/few[- ]shot/i,'explicit evaluation regime'],
 ['stages','SFT',/\bSFT\b|supervised fine[- ]tuning/i,'explicit training stage'],['stages','reward model',/reward model/i,'explicit training stage'],['stages','PPO',/\bPPO\b|proximal policy optimization/i,'explicit training stage'],
 ['attention','exact',/\bexact attention\b/i,'explicit attention property'],['attention','FlashAttention',/FlashAttention/i,'explicit attention implementation'],['attention','grouped-query attention',/grouped[- ]query attention/i,'explicit attention topology'],
 ['trace','thought',/\bthought\b/i,'explicit agent trace element'],['trace','action',/\baction\b/i,'explicit agent trace element'],['trace','observation',/\bobservation\b/i,'explicit agent trace element'],['trace','intermediate reasoning steps',/intermediate reasoning steps?|reasoning steps/i,'explicit reasoning trace'],
 ['method','odds ratio preference optimization',/odds ratio preference optimization|\bORPO\b/i,'explicit preference method'],['method','majority vote over sampled reasoning paths',/majority vote|self[- ]consistency/i,'explicit aggregation method'],
 ['algorithm','GRPO',/\bGRPO\b|group relative policy optimization/i,'explicit reinforcement algorithm'],['interaction','late interaction',/late interaction/i,'explicit retrieval interaction'],['retriever','dual-encoder dense retriever',/dual[- ]encoder|dense passage retriev/i,'explicit retriever architecture'],['operator','long convolutions',/long convolution/i,'explicit sequence operator']
];
const fieldFor=(query:string):PropositionField|undefined=>{const q=query.toLowerCase();if(/objective|self-supervised|corruption objective|learning signal/.test(q))return q.includes('objectives')?'objectives':'objective';if(/formulation|frame .*task|what does .* do|connect .* visual/.test(q))return'formulation';if(/parallelism|distributed across|parallel computation/.test(q))return'parallelism';if(/architecture|distribute tokens among experts/.test(q))return'architecture';if(/partition|partitioned/.test(q))return'partitioned_state';if(/component|intermediary module/.test(q))return q.includes('component')?'component':'components';if(/regime|zero-shot|one-shot|few-shot/.test(q))return'regimes';if(/stage|stages/.test(q))return'stages';if(/attention|topology/.test(q))return'attention';if(/trace|reasoning|intermediate outputs|event types alternate/.test(q))return'trace';if(/preference.optimization|select a final answer/.test(q))return'method';if(/reinforcement-learning algorithm/.test(q))return'algorithm';if(/compare .* representations/.test(q))return'interaction';if(/retrieval representation/.test(q))return'retriever';if(/operator/.test(q))return'operator';return undefined;};
function sentence(text:string,index:number):string { const start=Math.max(text.lastIndexOf('.',index)+1,text.lastIndexOf('\n',index)+1); const end=text.indexOf('.',index); return text.slice(start,end<0?text.length:end+1).trim(); }
export function extractResearchPropositions(document:ParsedDocument,query:string):ResearchProposition[] { const field=fieldFor(query);if(!field)return[];const out:ResearchProposition[]=[];for(const section of document.sections){for(const [ruleField,value,pattern,rule] of rules){if(ruleField!==field)continue;const match=pattern.exec(section.text);if(!match)continue;const sourceText=sentence(section.text,match.index);out.push({field,value,sourceText,locator:{section:section.heading,...(section.page===undefined?{}:{page:section.page}),...(section.pageId===undefined?{}:{pageId:section.pageId})},rule});}}return [...new Map(out.map(item=>[`${item.field}:${item.value}`,item])).values()];}
